bqplot/bqplot

bqplot/nbextension/Figure.js

@jasongrout This should solve the issue you were seeing earlier on the race condition with the svg transform.

Resolve race condition on resizing bqplot Figures

---

bqplot/pyplot/pyplot.py

Simple fix for the magic value in pyplot.

Fix sentinel check

---

README.md

This is an update to the README.md file updating the instructions for running bqplot from source. Fixes #11.

Update development installation instructions

---

setup.py

@jasongrout the implementation of which cannot be put in a separate file because relative imports only work from within a module.

Update setup.py to not run bower when it is absent

---

bqplot/interacts.py

Remove use of xrange

---

README.md

A couple of other fixes. A link for the license file and dependency on ipywidgets.

Fixes in readme

---

bqplot/__init__.py
bqplot/_version.py
setup.py

Reading version number from `bqplot._version`

---

bqplot/install.py

Besides this also changes the mode for install.py

Remove support for IPython 3.x in install.py

---

bqplot/nbextension/GridHeatMap.js
bqplot/nbextension/GridHeatMapModel.js
bqplot/nbextension/Tooltip.js
examples/GridHeatMap.ipynb

There was a bug in heat map where the number of rows and columns were interchanged when assigning the data. Also, there was a minor fix in the notebook. with the print function.

Bug fix in drawing heatmap

---

bqplot/axes.py

allow None for Axis.tick_values

---

README.md

Adding readthedocs badges to the README

---

examples/Basic Plotting.ipynb
examples/Boxplot.ipynb
examples/Candles.ipynb

1. Cleaned up 'Basic Plotting' to remove unnecessary functions and variables, using better colors and tick marks
2. Cleaned up BoxPlot and Candles notebooks to remove the use of interactions (which should not be present in these examples), and made the code concise

Cleanup of 'Basic Plotting', 'Box Plot' and 'Candles' example notebooks

---

bqplot/marks.py

Update default stroke-width in Lines

---

bqplot/nbextension/Lines.js

Further fix for `curves_subset`

---

bqplot/nbextension/Boxplot.js
bqplot/nbextension/bqplot.less

Also some code formatting in Boxplot.js.

Fix boxplot default stroke color

---

bqplot/marks.py
bqplot/nbextension/Bars.js
bqplot/nbextension/BrushSelector.js
bqplot/nbextension/Hist.js
bqplot/nbextension/Pie.js
docs/source/conf.py
examples/Mark Interactions.ipynb

- no need to call `self.on_msg(self._handle_custom_msgs)` in `Scatter.__init__` since it is already called in `Mark.__init__`.
- a couple of minor changes in the docs configuration.
@ssunkara1 let me know if this is fine with you.

Scatter event fixes

---

bqplot/nbextension/Toolbar.js

No need to require bootstrap or utils.

Less requirements for toolbar

---

bqplot/nbextension/Mark.js

@SylvainCorlay Please have a look.

Fix for marks not getting removed 

---

bqplot/nbextension/AxisModel.js
bqplot/nbextension/MarkModel.js
bqplot/nbextension/Toolbar.js
bqplot/toolbar.py

Backported from the ipywidget 5dev compatibility branch.

Fix issues with default toolbar persistence to page reload

---

bqplot/nbextension/PanZoom.js

Mousewheel event support in Firefox

---

bqplot/nbextension/Lines.js

Fixed a small bug when updating the legend style.

Fixed legend style updating, deleted obsolete 'legend_click' function

---

bqplot/nbextension/AxisModel.js
bqplot/nbextension/BarsModel.js
bqplot/nbextension/BoxplotModel.js
bqplot/nbextension/ColorScaleModel.js
bqplot/nbextension/DateColorScaleModel.js
bqplot/nbextension/GridHeatMapModel.js
bqplot/nbextension/HistModel.js
bqplot/nbextension/LinearScaleModel.js
bqplot/nbextension/LinesModel.js
bqplot/nbextension/LogScaleModel.js
bqplot/nbextension/MapModel.js
bqplot/nbextension/MarkModel.js
bqplot/nbextension/OHLCModel.js
bqplot/nbextension/OrdinalScaleModel.js
bqplot/nbextension/PanZoomModel.js
bqplot/nbextension/PieModel.js
bqplot/nbextension/ScatterModel.js

@ssunkara1 this is work in progress to use the first state in the mark's initialize method.

Use first state in initialize

---

bqplot/nbextension/Mark.js
bqplot/nbextension/MarketMap.js

Reverting tooltip changes which do not work in full screen

Reverting tooltip changes

---

bqplot/pyplot.py
examples/Pyplot.ipynb

Fixed the bug with `clear()`.
Edited the example notebook to change the order of the different examples.

Pyplot modifications

---

README.md
bqplot/__init__.py

This use the new nbextension machinery for notebook 4.2.

Use new nbextension machinery

---

bqplot/__init__.py
js/src/extension.js
js/src/index.js
js/webpack.config.js

Separate out the nbextension webpacked module from bqplot.

Separate extension from main bqplot js module

---

js/src/extension.js
js/webpack.config.js
setup.py

Make two webpack targets, one for the nbextension and the other one for the embeddable bundle.

Embeddable

---

js/src/extension.js
js/webpack.config.js
setup.py

For the notebook extension and bqplot itself.

Make separate bundles

---

js/src/BrushSelector.js

Fixes #118 . Thanks to @ssunkara1 .

Multi selector fix

---

js/src/Axis.js
js/src/ColorAxis.js
js/src/Figure.js

Don't use css transforms because ie11 does not support it

---

js/src/TooltipModel.js
js/src/index.js

The new custom model for tooltip was not being correctly exported.

Fix Tooltip Model

---

README.md

Now we have a one-step install with conda. @jasongrout @ssunkara1.

Adding conda instructions

---

examples/Scatter.ipynb

Fixes #133 @ssunkara1 @SylvainCorlay

Change deprecated enable_add call

---

examples/Interaction Layer.ipynb

Fixes #93 .
Also addresses #130 for the Interaction Layer notebook

Interaction Layer Notebook fix

---

bqplot/figure.py
js/package.json
js/src/Figure.js
js/src/FigureModel.js

This should fix the min-width, min-height nonsense.
@albop

Fix bqplot layout issues

---

bqplot/figure.py
js/package.json
js/src/Figure.js
js/src/FigureModel.js

WIP Revert "Fix bqplot layout issues"

---

bqplot/marks.py
examples/Label.ipynb
examples/Wealth of Nations.ipynb
js/src/Label.js

Adding a drag behavior for `Label`.
The `Label` coordinates `x` and `y` are updated accordingly at the end of the drag.
This also cleans up the `Label.js` code.

Draggable Label

---

js/src/Lines.js

Fix Marker Color Bug

---

README.md

Change hyperlink of picture

---

README.md

README link changes

---

bqplot/marks.py
examples/Scatter.ipynb
js/src/Scatter.js

Update Hover Styles

---

bqplot/marks.py

The default behavior for fill colors will be to match line colors

changed default fill_colors to none in Lines

---

README.md
js/src/FigureModel.js

@SylvainCorlay All set. If we merge Sri's `numpy` fix, we can aim for a release this week?

Fix default for styles

---

bqplot/nbextension/MarketMap.js

@ssunkara1 Should fix the issue we were having

Fix MarketMap Bug on 0.5.x

---

examples/Applications/Wealth of Nations.ipynb

@rmenegaux Yours to review
@stonebig Might be of interest

Added path of a country on hover in Wealth of Nations

---

examples/Marks/Market Map.ipynb
js/src/MarketMap.js

@ssunkara1 This fixes the `colors` bug. Should I open a corresponding PR to 0.5.x?

Add listeners for colors in MarketMap

---

bqplot/figure.py
bqplot/pyplot.py
examples/Basic Plotting/Pyplot.ipynb
js/src/Mark.js
js/src/MarketMap.js

Tooltip positioning bug fix. Pyplot hline and vline.

---

bqplot/figure.py
bqplot/pyplot.py
examples/Pyplot.ipynb

Added functions for hline, vline and grids in pyplot.
Changed the example notebook to be the same as the version in master.

hline vline and grids in pyplot for 0.5.x

---

examples/Applications/Wealth of Nations.ipynb
setup.py

This depends on https://github.com/ipython/ipywidgets/pull/633 which adds a front-end only `Play` widget that uses the event loop of the browser.
Will require a release of ipywidgets before merging.

Use Play Widget

---

setup.py

This is the first on conda-forge with the play widget.

Require ipywidgets 5.2.2

---

js/src/Lines.js
js/src/LinesModel.js

remove opacity from Lines mark data

---

bqplot/marks.py
js/src/Map.js

Remove Map `selected` overload of None

---

bqplot/pyplot.py
bqplot/scales.py

This is an equivalent to PR #183 . This is for the master branch rather than for 0.5.x

Pyplot adding order for compatible scales

---

bqplot/axes.py

@ssunkara1 @SylvainCorlay Now that the grid lines are more discreet, we should probably make them the default

Added 'solid' grid lines by default

---

js/src/BarsModel.js
js/src/BoxplotModel.js
js/src/ColorScaleModel.js
js/src/DateColorScaleModel.js
js/src/DateScaleModel.js
js/src/GeoScaleModel.js
js/src/GridHeatMapModel.js
js/src/HistModel.js
js/src/LinearScaleModel.js
js/src/LinesModel.js
js/src/LogScaleModel.js
js/src/MapModel.js
js/src/MarkModel.js
js/src/OHLCModel.js
js/src/OrdinalScaleModel.js
js/src/PanZoomModel.js
js/src/PieModel.js
js/src/ScaleModel.js
js/src/ScatterModel.js

@dmadeka this should solve the issue with bqplot figures not showing on ipywidgets master.

6x-compat call to initialize

---

examples/Basic Plotting/Basic Plotting.ipynb

The variable wasn't used correctly in one place @ssunkara1

Fix basic plotting notebook

---

bqplot/figure.py
bqplot/nbextension/Figure.js

@ssunkara1 This should be useful for the 0_5_master branch, backports #166

Backport save_png method

---

bqplot/pyplot.py

Allow multiple vline and hline

---

bqplot/pyplot.py
js/src/bqplot.less

Fix dark theme for bqplot

---

LICENSE
examples/Marks/Market Map.ipynb

@SylvainCorlay @ssunkara1 This adds the License for the two csv files in the `data_files` folder

Update examples' License

---

examples/Basic Plotting/Introduction.ipynb
examples/Index.ipynb
examples/Introduction.ipynb

@SylvainCorlay @ssunkara1 @rmenegaux Comments welcome

First pass at an Introduction notebook

---

bqplot/marks.py
js/src/GridHeatMap.js
js/src/GridHeatMapModel.js

@ssunkara1 @vedantam This should patch the issue, probably not the best way to handle it though

Add null color for GridHeatMap

---

README.md

https://twitter.com/ivanov/status/355409397339521025 :)

fix IPython spelling

---

js/src/BrushSelector.js

BrushSelector does not work in master now.

Brush Selector bug fix

---

bqplot/marks.py
examples/Applications/Wealth of Nations.ipynb
examples/Marks/Label.ipynb
js/src/Label.js
js/src/LabelModel.js
js/src/Scatter.js

@SylvainCorlay @ssunkara1 This is per our discussion that `Label` should take multiple values. I think globally, this PR will be redundant soon, but is necessary.
I think `Scatter`, `Label` (or even `Image`) is basically placing an element at a certain point on the scale. It should probably be moved to a global `Object` (or global `Scatter` mark like Altair) and have some custom behaviours, but the drag, placement, coloring etc. should all be an `Objects` property. 
PS `Objects` should allow us to place any DOM element at the point right, so why not put an entire `Figure` so as to have a `Scatter` of `Figure`s?

Allow Label to take multiple values

---

bqplot/pyplot.py
examples/Pyplot.ipynb

Returning `hline`, `vline` and `figure`. Passing `kwargs` to `hline` and `vline`.

Pyplot changes backport. 

---

examples/Marks/Map.ipynb
js/package.json
js/src/Axis.js
js/src/Bars.js
js/src/Boxplot.js
js/src/BrushSelector.js
js/src/ColorAxis.js
js/src/FastIntervalSelector.js
js/src/Figure.js
js/src/FlexLine.js
js/src/GridHeatMap.js
js/src/HandDraw.js
js/src/Hist.js
js/src/IndexSelector.js
js/src/Interaction.js
js/src/Label.js
js/src/LassoSelector.js
js/src/Lines.js
js/src/Map.js
js/src/Mark.js
js/src/MarketMap.js
js/src/OHLC.js
js/src/PanZoom.js
js/src/Pie.js
js/src/Scatter.js
js/src/Selector.js
js/src/SquareMarketMap.js
js/src/Toolbar.js
js/src/Tooltip.js

This comes on the top of #258 . closes #258

Set element

---

bqplot/traits.py
examples/Interactions/Interaction Layer.ipynb
setup.py

Date trait fix

---

bqplot/traits.py

Pandas DF Trait Fix

---

js/src/SquareMarketMap.js

Remove resizable call

---

bqplot/traits.py

@ssunkara1 @SylvainCorlay This is the other fix

Fix set value for Pandas

---

bqplot/traits.py
js/src/ScatterModel.js

@ssunkara1 @SylvainCorlay Here is the change. Big thanks to @ssunkara1 , but @SylvainCorlay you should test

NdArray Trait Fixes

---

bqplot/traits.py

Fixing issue with default_value for custom traits

---

js/src/Axis.js
js/src/bqplot.less

This is how the new version looks. Please let me know what you think.

Dark theme styling changes

---

bqplot/figure.py
bqplot/pyplot.py
examples/Basic Plotting/Pyplot.ipynb

They are similar to those of `matplotlib.pyplot`.
I also force the values of the `title_style` dict to be of type `Unicode`.

Adding title and legend functions to pyplot

---

setup.py

The name of the dependency is misspelled.

Fixing traittypes dependency

---

js/src/Axis.js

Axis tick_values fix

---

bqplot/axes.py
bqplot/figure.py
bqplot/interacts.py
bqplot/market_map.py
bqplot/marks.py
bqplot/traits.py
examples/Applications/Wealth of Nations.ipynb
examples/Interactions/Interaction Layer.ipynb
examples/Introduction.ipynb
examples/Marks/Market Map.ipynb
js/src/LabelModel.js

Migrate to a traittypes implementation of a `DataFrame` trait.

Traittypes dataframe

---

setup.py

Update traitlets requirement

---

bqplot/marks.py
js/src/Label.js
js/src/Scatter.js

Fixes issue #338 
Thanks Daniel for pointing this out.

Drag bug fix in Scatter and Label

---

.gitignore
.travis.yml
bqplot/__init__.py
bqplot/figure.py
js/package.json
js/src/Figure.js
js/src/FigureModel.js
js/src/MarketMap.js
js/src/bqplot.less
js/src/labplugin.js
js/webpack.config.js

I rebased #337, which itself includes several other PRs.

Rebased JLab compatibility

---

.travis.yml
js/package.json
js/src/Toolbar.js
js/src/labplugin.js
js/webpack.config.js

Update for ipywidgets 6.0 beta

---

bqplot/figure.py
js/src/Figure.js

Fixed the issue where width and height are being set to -120.
Changed the default figure to be bigger. I felt the current default is too small.
@rmenegaux @SylvainCorlay @jasongrout

Minor bug fix and Styling changes

---

MANIFEST.in
js/package.json
setup.py

Add staticlab files to wheel

---

js/src/Toolbar.js

The pan-zoom button is a toggle.

Fix toolbar css for ipywidgets 6.0

---

README.md

Updated README to include a simple example

---

README.md

Make changes to README

---

bqplot/pyplot.py
examples/Basic Plotting/Pyplot.ipynb

@SylvainCorlay @jasongrout Does the update work for all versions of Python?
I dont want to do {**x, **y} to merge the two dictionaries.

Fix data attribute

---

examples/data_files/world_map_codes.csv

Make World Map Codes useful

---

bqplot/market_map.py
js/package.json
js/src/Figure.js
js/src/Lines.js
js/src/MarketMap.js
js/src/Tooltip.js
js/src/bqplot.less
setup.py

Also, make the top-level element a div, and relayout on the after-show phosphor message.

Update to latest widgets

---

docs/environment.yml
docs/source/conf.py
docs/source/usage.rst
setup.py

This requires the current master branch of ipywidgets (or the ipywidgets 6.0.0b6 when it is out).

Use the bqplot sphinx extension for the usage example

---

js/src/LogScaleModel.js

typo in LogScaleModel

---

examples/Interactions/Interaction Layer.ipynb

Documentation for example of MultiSelector

---

js/package.json

@jasongrout this works in jupyterlab 0.13.

Update to jupyterlab 0.13

---

bqplot/marks.py
bqplot/pyplot.py
examples/Marks/Bars.ipynb
js/src/Bars.js
js/src/BarsModel.js
js/src/Figure.js
js/src/MarkModel.js

@ssunkara1 @SylvainCorlay If we merge the `HeatMap` I think we will have all relevant Marks covered I believe.
Fixes #402

First pass at Horizontal bars

---

js/package.json

Add bqplot group email to package.json

---

js/src/LogScale.js

log sclae bug

---

examples/Marks/Market Map.ipynb
js/src/MarketMap.js

NaN color fix for MarketMap

---

examples/Marks/Scatter.ipynb
js/src/Tooltip.js

tooltip fixes

---

examples/Applications/Visualizing the US Elections.ipynb

The Elections notebook was the only one I could find not up to date

Using Layout in example notebooks

---

examples/Interactions/Interaction Layer.ipynb

Replacing `Label` with `HTML` so that the text is not cutoff and a few other minor clean-ups.

Clean up interaction layer example notebook

---

js/src/Figure.js
js/src/MarketMap.js

fixes #446. Also moves the `tooltip` when we are moving the mouse on a cell in the `Marketmap`

Marketmap tooltip bug fixes

---

js/src/Figure.js
js/src/MarketMap.js

`MarketMap` was not listening to `change:scales`.

market map scale change bug fix

---

bqplot/marks.py
examples/Advanced Plotting/Animations.ipynb
examples/Marks/Pie.ipynb
js/src/Pie.js
js/src/PieModel.js
js/src/bqplot.less

1. Enhanced transitions of Pie to take into account missing data
2. Made display_labels enum with 'inside', 'outside' and 'none' options
3. Added display_values option (and values_format) to display values
4. Enhanced example noteboks to reflect the above changes

Pie enhancements

---

README.md

The old room is not in use anymore.

Update gitter badge

---

examples/Applications/Visualizing the US Elections.ipynb

The Elections example was broken after the changes to make the graphs visible in nbviewer.

Fixing Elections example

---

.mailmap

Change my mailmap

---

.gitignore
MANIFEST.in
bqplot/__init__.py
js/package.json
jslab/index.js
jslab/package.json
setup.py

This is definitely still a work in progress.

WIP update to latest Jupyter widgets package.

---

js/src/Axis.js
js/src/AxisModel.js
js/src/BaseModel.js
js/src/ColorScale.js
js/src/Figure.js
js/src/FigureModel.js
js/src/GeoScale.js
js/src/HandDrawModel.js
js/src/Interaction.js
js/src/Map.js
js/src/Mark.js
js/src/MarkModel.js
js/src/MarketMap.js
js/src/MarketMapModel.js
js/src/PanZoom.js
js/src/PanZoomModel.js
js/src/Scale.js
js/src/SelectorModel.js
js/src/SquareMarketMap.js
js/src/Toolbar.js
js/src/Tooltip.js
js/src/TooltipModel.js
js/src/extension.js
js/webpack.config.js

CC @maartenbreddels - these are some more changes we needed to make to update the package to the latest jupyter widgets.

Update to use the new Jupyter package names

---

bqplot/figure.py
bqplot/toolbar.py
js/src/Toolbar.js

The pan/zoom was not correctly being instantiated on the js side.

[WIP] Fix panzoom widget

---

bqplot/marks.py

Add doc strings for newer Marks

---

bqplot/pyplot.py
examples/Basic Plotting/Pyplot.ipynb

Adding GridHeatMap in pyplot

---

jslab/package.json

Needed for the latest @jupyter-widgets/jupyterlab-manager

Version update for jupyterlab

---

js/src/HistModel.js

Normalized Histogram normalization was broken before. We were ignoring the width of the bin. Also handling the no data case gracefully.

fixing normalized histogram

---

.gitignore
MANIFEST.in
bqplot/__init__.py
js/package.json
jslab/package.json
setup.py

@jasongrout Can you have a quick look at this?

backporting to 0.9.x: removing static lab etc in 0_9_master to fix travis build

---

bqplot/figure.py
js/src/Figure.js
js/src/FigureModel.js
js/src/bqplot.less

@dmadeka, @ssunkara1 
First stab at customizing legend and legend text

Added ability to change legend_style and legend_text

---

README.md
jslab/Readme.md

(and update the ipywidgets version in the readme).
CC @stonebig

Add installation instructions for jlab

---

bqplot/marks.py
bqplot/scales.py
js/src/GeoScaleModel.js

Fixes #550.
This also fixes a few little inconsistencies in the documentation.

add translate argument for AlbersUSA projection

---

bqplot/marks.py

Added documentation for the Image mark.
Working on a pyplot function as well as an example notebook.

Addons for the Image mark

---

bqplot/axes.py
examples/Advanced Plotting/Axis Properties.ipynb
js/src/Axis.js
js/src/AxisModel.js
js/src/bqplot.less

- Adding styling to the ticks
- Fixing the anti-aliasing bug where certain grid lines do not show up

Axis changes

---

bqplot/market_map.py

I'm getting errors from trying to compare the data frame traits with just ==. We should be using the pandas .equals method.

Compare data frame traits using the pandas equals function

---

bqplot/marks.py
examples/Marks/Graph.ipynb
js/src/Graph.js

Enabled on_element_click for Graph mark

---

.travis.yml
test-environment.yml

This ensures that the lab extension installs correctly and that the app loads without any console errors or uncaught errors.

Add JupyterLab integration test to Travis Script

---

js/src/Image.js
js/src/ImageModel.js

The Image was sometimes not rescaling at all (some kind of a race condition). This cleans up and fixes that issue.
Animation is an added bonus.

Race condition in the Image

---

js/src/Image.js

Remove ES6 syntax

---

examples/Applications/Feature_Vector_Distribution-Iris-Digits.ipynb

The feature in the second dropbox was not initialised correctly.
I also removed the extra axes of the histograms.

Fix feature 2 in iris example

---

bqplot/interacts.py
bqplot/marks.py
bqplot/scales.py
bqplot/traits.py
examples/Basic Plotting/Pyplot.ipynb
js/src/Axis.js
js/src/Bars.js
js/src/BrushSelector.js
js/src/GridHeatMap.js
js/src/MarketMap.js
js/src/ScatterBase.js
js/src/Selector.js
js/src/extension.js

- Used https://github.com/client9/misspell to identify and fix typos throughout the repo

Fixed typos

---

bqplot/__init__.py
bqplot/axes.py
bqplot/colorschemes.py
bqplot/default_tooltip.py
bqplot/figure.py
bqplot/interacts.py
bqplot/market_map.py
bqplot/marks.py
bqplot/pyplot.py
bqplot/scales.py

1. Fixed PEP8 warnings in the python files
2. Tested to make sure all the example notebooks are running fine

Pep8 cleanup

---

examples/Marks/Object Model/Scatter.ipynb
js/src/ScatterBase.js

Points in a Scatter can be deleted by setting `scatter.interactions = {'click': 'delete'}` and clicking the unwanted points.
This solves issue #253

Enabling delete in Scatter

---

js/package-lock.json
js/src/Scatter.js
js/src/ScatterBaseModel.js
js/test/scatter.ts

TODO:
-  [x] expose bug
This should fix #606

WIP: Scatter style bug

---

setup.py

some versions of pip or distutils don't want this

License should be small caps

---

bqplot/marks.py

Fixes https://github.com/bloomberg/bqplot/issues/727

Don't squeeze array because of single stacked bar

---

js/src/BrushSelector.js

Fix: empty brush updates brush.selected

---

js/src/GridHeatMap.js

Apply selected/unselected styles on GridHeatMap redraw

---

bqplot/pyplot.py

fixed an issue with marker strings ("default_colors" renamed to "colors")

---

bqplot/figure.py
js/src/Figure.js
js/src/FigureModel.js

caused by a non-physical min_asect_ratio of 0. Also cleans up the min_width parsing.

Figure: fixes annoying Infinity error 

---

bqplot/figure.py
js/src/Figure.js
js/src/FigureModel.js

Figure: support for pixel_ratio for WebGL pixel size control

---

js/src/BrushSelector.js

fixed an issue where 'selected' wasn't getting updated on empty brush

---

js/src/Pie.js
js/src/bqplot.less

Pie polylines fix

---

js/src/ColorAxis.js

Fixup color axis domain

---

bqplot/traits.py
js/src/LinesModel.js
js/src/utils.js
js/test/lines.ts
js/test/widget-utils.ts
tests/conftest.py
tests/marks_test.py

As noticed in #770, since the move to binary transfer, ordinal values are not supported.

Ordinal fix/support for binary

---

js/src/BrushSelector.js

Silence brush events on selected_changed

---

js/src/MarketMap.js

aligning the labels to be in the center of the tiles (by using CSS style **dominant-baseline: central**)

centered the labels

---

bqplot/market_map.py
examples/Marks/Object Model/Market Map.ipynb
js/src/MarketMap.js

1. Cleaned up selections (clicking and selecting tiles) to take care of special characters in names
2. Added a bool option to freeze/unfreeze tooltips. This way user can decide when to freeze the tooltips or when to make them follow the mouse

Tile map fixes/enhancements

---

bqplot/marks.py
examples/Marks/Object Model/GridHeatMap.ipynb
js/src/GridHeatMap.js

Adding annotations to heatmap

---

js/src/PanZoom.js
js/src/ScaleModel.js

bugfix: make panzoom take scale-reversal into account

---

js/src/Axis.ts
js/src/Bars.ts
js/src/Figure.ts
js/src/Mark.ts
js/src/Scale.ts
js/src/Tooltip.ts

This PR starts converting files to use es6 classes.

Next steps for typescript integration

---

js/src/Bars.ts
js/src/BarsModel.ts
js/src/BaseModel.ts
js/src/Boxplot.ts
js/src/BoxplotModel.ts
js/src/BrushSelector.ts
js/src/Interaction.ts
js/src/Mark.ts
js/src/OHLC.ts
js/src/Selector.ts
js/src/utils.ts

Move more files to use es2015 classes

---

.travis.yml
js/package.json
js/test/bars.ts
js/test/lines.ts
js/test/scatter.ts
js/test/utils.ts

That's an attempt to fix JavaScript tests. Currently, all tests are passing expect one.

Fixing tests

---

.travis.yml
js/karma.conf.js
js/src/Figure.ts
js/src/Label.ts
js/src/LabelModel.ts
js/src/LassoSelector.ts
js/src/MapModel.ts
js/src/MarketMap.ts
js/src/MarketMapModel.ts
js/test/bars.ts
js/test/binary_serialization.ts
js/test/dummy-manager.ts
js/test/index.ts
js/test/lines.ts
js/test/scales.ts
js/test/scatter.ts
js/test/utils.ts
js/test/widget-utils.ts
js/tsconfig-test.json

I think this finishes out the conversion to es6 classes.

Finish converting to es6 classes

---

bqplot/market_map.py
examples/Marks/Object Model/Market Map.ipynb
js/package-lock.json
js/src/MarketMap.ts

This requires #836 to be merged first.
There are still issues with the mouse event handlers in MarketMap that need to be fixed.

Forward port of #785

---

js/src/Boxplot.ts

- adds selection to Boxplot
- follows the patterns in Bar plot
- selections are made by clicking box rectangle
- interactions, selected_style, and unselected_style parameters passed into Boxplot constructor are used for enabling and styling the selections

add support for Boxplot selection

---

js/src/Pie.ts
js/src/PieModel.ts

Fix Pie chart

---

js/src/extension.ts
js/tsconfig.json

Convert the last js file to typescript

Convert the last js file to typescript

---

js/src/MarketMap.ts

This fixes your issue concerning the color in MarketMap @ChakriCherukuri.
I'm not sure it's the proper fix though, do you mind looking at it @maartenbreddels ?

Fix MarketMap color when data is NaN

---

js/src/utils.ts

This should fix #866.
The bug has been introduced in 815a2de887c8d4e54e963f422149b4c88ea48de9

Fix date serialization

---

examples/Marks/Object Model/GridHeatMap.ipynb
examples/Marks/Pyplot/GridHeatMap.ipynb
js/src/GridHeatMap.ts

*Issue number of the reported bug or feature request: #875 
d3 upgrade to v5 throws an error in d3.format when null is passed
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Tested GridHeapMap notebook to make sure all cells render
Add any other context about your contribution here.

Grid heatmap fix

---

setup.py

This error confused me when I was building several packages in one go

Fix error message to mention bqplot

---

README.md

We deleted the stable branch since it had fallen way behind.

Delete stable branch

---

bqplot/figure.py
js/src/FigureModel.js

If we have an aspect ratio of 0, we end up dividing by 0, and have to deal with infinity, etc.

Aspect ratios must be positive

---

bqplot/figure.py
bqplot/marks.py
examples/Marks/Object Model/GridHeatMap.ipynb
examples/Marks/Pyplot/GridHeatMap.ipynb
js/src/Figure.js
js/src/GridHeatMap.js

Gridheatmap fix

---

js/src/Bars.ts

Fix Bar padding update
Fix rangeBand -> bandwidth

Fix Bar padding update

---

js/package-lock.json
js/src/Boxplot.ts

Fixed boxplot: rangeBand -> bandwidth

---

bqplot/figure.py
bqplot/marks.py
examples/Marks/Object Model/GridHeatMap.ipynb
examples/Marks/Pyplot/GridHeatMap.ipynb
js/src/GridHeatMap.ts

Porting Chakri's Gridheatmap fix #902 to master

Porting Gridheatmap fix #902 to master

---

js/src/ColorScaleModel.ts
js/src/DateColorScaleModel.ts

Fix ColorScaleModel domain type

---

js/src/OHLCModel.ts

Fix missing OHLC model attribute

---

js/src/Figure.ts
js/src/Mark.ts
js/src/MarketMap.ts

Fix tooltip layout issue

---

js/src/Bars.ts

Exactly the same issue as in #916, this time with Bars marks

Fix Bars multi-selection

---

bqplot/marks.py
js/src/Boxplot.ts
js/src/Graph.ts
js/src/GridHeatMap.ts
js/src/Map.ts
js/src/MapModel.ts
js/src/Pie.ts

Exactly the same issue as in #916, this time with Pie, GridHeatMap, Map, BoxPlot and Graph marks

Mark selection fix

---

bqplot/marks.py
js/src/Label.ts
js/src/LabelModel.ts

This fixes #925
Backport PR coming

Fix labels models

---

js/src/Figure.ts
js/src/FigureModel.ts

Fix figure model

---

js/src/ColorScaleModel.js
js/src/DateColorScaleModel.js
js/src/DateScaleModel.js
js/src/OrdinalScaleModel.js

0.11.x Scales models fix

---

js/src/ColorScaleModel.ts
js/src/DateColorScaleModel.ts
js/src/DateScaleModel.ts
js/src/OrdinalScaleModel.ts

Fix missing attributes in the Scales models

Fix Scales models

---

bqplot/marks.py
js/src/GridHeatMap.ts
js/src/GridHeatMapModel.ts

Fix GridHeatMap color update

---

js/src/OrdinalScale.ts

Fix offset issue in OrdinalScale

---

bqplot/marks.py

Removed redundant print statements from marks.py

remove redundant print statements

---

js/src/HeatMap.ts

Fix heatmap in the case of a reversed scale

---

.travis.yml

Cf https://github.com/conda/conda/issues/9337

Fixup CI breakage that is due to conda bug.

---

js/src/Axis.ts
js/src/ColorAxis.ts

Fix Axis size issues

---

bqplot/scales.py
js/src/OrdinalColorScaleModel.js
js/src/index.js

Signed-off-by: idafna <idafna@bloomberg.net>
This is the 0.11.x implementation of #980

Add OrdinalColorScaleModel to 0.11.x

---

js/src/HeatMap.ts

- Factorize `get_x_plotting_data` and `get_y_plotting_data` into
`getPlottingData`
- Factorize `get_x_padding` and `get_y_padding` into `getPadding`
- snake_case to camelCase
- functions to arrow functions

Cleaning Heatmap implementation

---

bqplot/marks.py
js/src/Hist.ts
js/src/HistModel.ts
js/src/test/bars.ts
js/src/test/hist.ts
js/src/test/index.ts
js/src/test/scatter.ts
js/src/test/widget-utils.ts

This will fix the two first tasks on #995

Hist respect colors

---

bqplot/_version.py
js/package-lock.json
js/package.json

Signed-off-by: Sylvain Corlay <sylvain.corlay@gmail.com>
Releasing 0.12.2

Release 0.12.2

---

js/src/Pie.ts
js/src/PieModel.ts
js/src/test/index.ts
js/src/test/pie.ts
js/src/test/widget-utils.ts

Signed-off-by: martinRenou <martin.renou@gmail.com>
Fix #989

Pie: Fix label display and update

---

bqplot/axes.py

Fix simple typo: resepect -> respect

---

bqplot/interacts.py
bqplot/marks.py

Fixed a few Sphinx warnings.
Built the docs and the warnings are gone.

DOC: Fix a few Sphinx warnings

---

js/src/GridHeatMap.ts
js/src/test/gridheatmap.ts

GridHeatmap: Fix selection

---

js/src/MarketMap.ts

MarketMap: Fix text style at creation

---

bqplot/axes.py
js/src/AxisModel.ts

Axis: Fix axis side validation

---

bqplot/axes.py
js/src/AxisModel.ts

Revert #1007 
This will fix #1024 
But it will reopen #956

Revert #1007

---

bqplot/traits.py

I suppose this is a leftover. It is not used anywhere.

Remove unused function

---

bqplot/_version.py
js/package-lock.json
js/package.json

*Issue number of the reported bug or feature request: #<number>*
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.

Release 0.12.4

---

bqplot/_version.py
js/package-lock.json
js/package.json

*Issue number of the reported bug or feature request: #<number>*
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.

Release 0.12.5

---

js/src/Pie.ts
js/src/test/pie.ts

This also fixes issues with selected-style and font-style not being properly applied

Pie: Split draw function into sub-functions

---

js/src/Figure.ts

Relayout on after-attach event

---

js/package.json

Add keywords to package.json

---

js/src/BarsModel.ts

Drop NaNs in stacked bar

---

examples/Marks/Object Model/Bars.ipynb

Adding bar labels to the Bars mark example. 
Checked that the code ran correctly in the notebook.

Add bar labels to the Bars mark example

---

bqplot/traits.py

Revert function removal #1031

---

js/src/Figure.ts
js/src/MarketMap.ts

This will fix #1015, it is an update of the MarketMap figure related to #993 and #982

MarketMap: Debounce relayout calls

---

bqplot/traits.py
js/src/PanZoom.ts

Fix PanZoom with date scale

---

js/src/ColorScaleModel.ts

Adjust mid in ColorScale domain

---

js/src/MarketMap.ts
js/src/ScatterBase.ts
js/src/utils.ts

This fixes #1108 (it's what is described as the "quicker fix" in the issue)

preserve array attributes when duplicating them

---

js/src/Bars.ts

Should fix https://github.com/bqplot/bqplot/issues/1110

Fix bars coloring computation

---

js/src/Bars.ts

Fix Bars opacities

---

js/src/Bars.ts
js/src/Boxplot.ts
js/src/Hist.ts
js/src/Lines.ts
js/src/ScatterBase.ts

Fix legends

---

js/src/Mark.ts

This attribute does not seem to be used anywhere

Remove colors attribute from Mark

---

js/src/Lines.ts

This should fix line removing:

Fix lines removing

---

bqplot/traits.py
js/src/serialize.ts
js/src/test/binary_serialization.ts
js/src/test/widget-utils.ts
tests/binary_serialization_test.py
tests/marks_test.py

Add support for serializing list of variant-sized lists

---

js/src/test/lines.ts

Run remaining test

---

js/src/Graph.ts

- `that` -> `this`
- remove `Graph.get_node_color` and replace it with `Mark.get_mark_color` everywhere

Graph: cleaning

---

js/less/bqplot.less
js/src/Tooltip.ts

Old visual aspect:
New visual aspect:

Improve tooltip styling

---

js/less/bqplot.less

Fixup data selector

---

.travis.yml
js/src/bqplot.less

Fixup jupyterlab1 theme support

---

examples/Tutorials/Brush Interval Selector.ipynb

Update Brush Interval Selector.ipynb

---

js/src/Bars.ts
js/src/BarsModel.ts

Fixup bars nans

---

js/src/Bars.ts

This should fix the issue mentioned by @maartenbreddels here: https://github.com/bqplot/bqplot/commit/d5408fa38e5039e289b8df5c429f44047c0237af#r39828724

Bars: Use arrow function

---

js/src/Figure.ts
js/src/test/figure.ts

Fixes a part of #1174
cc @rosteen
Note that does not fix the issues with normal images as reported in #1174 (separate PR coming)

fix: WebGL content was not visible in screenshots (png/svg)

---

js/src/Figure.ts
js/src/Image.ts
js/src/test/common.ts
js/src/test/image.ts
js/src/test/index.ts
js/src/test/widget-utils.ts

cc @rosteen
This fixes screenshots, which did not include images. Images referred to blob URLs, we transform them to dataUrl's so they are embedded in the svg (and thus also appear in the png)

Fix screenshot image

---

js/src/Lines.ts

Lines: Fix click event

---

js/src/Mark.ts

Selection: Update attributes (e.g. "selected") before sending comm msgs

---

setup.py

Setup.py: Do not install tests

---

README.md

I think this is the right one.

Link on readme gif links to a 404

---

examples/Index.ipynb

Hi, I fixed the broken link to the ScatterMega notebook

fixed link to ScatterMega

---

js/src/BrushSelector.ts
js/src/Selector.ts

Fix https://github.com/bqplot/bqplot/issues/1180
See https://github.com/d3/d3-brush/issues/43

BrushIntervalSelector

---

js/less/bqplot.less
js/src/BrushSelector.ts
js/src/LinearScale.ts
js/src/Selector.ts

I looked for having a mixin class to reduce the code duplication in this file, unfortunately it seems impossible at the moment when base classes are abstract https://github.com/microsoft/TypeScript/issues/29653

Refactor BrushSelector

---

setup.py

Fixes #1234 
we might want to upstream this to jupyter_packing.

fix: source distribution with prebuild js should skip js_command

---

.github/workflows/build.yml
test-environment.yml

Maybe at some point we can get rid of Travis

Add Github action for checking sdist and wheel

---

.github/workflows/build.yml
bqplot/__init__.py
bqplot/_version.py
bqplot/install.py
bqplot/marks.py
bqplot/pyplot.py
bqplot/traits.py
test-environment.yml

See https://github.com/bqplot/bqplot/issues/1185

Add flake8 check and run Python tests on Github Actions

---

js/src/MarketMap.ts

fix: market map was still using .styles

---

js/src/MarketMap.ts

Fix market map styles

---

.github/workflows/build.yml
pytest.ini
test-environment.yml

This would have helped catch this issue: https://github.com/bqplot/bqplot/pull/1296

Use nbval on the CI

---

js/src/Hist.ts

It was not possible to select the last bin
cc. @kaiayoung

Fix hist selection

---

js/less/bqplot.less

Graph: Remove text shadow

---

examples/Marks/Object Model/Graph.ipynb
js/src/Graph.ts

Fix Directed Graph Mark

---

ui-tests/package.json

Tests were not passing anymore for me locally

UI-tests: Increase diff threshold

---

js/src/BoxplotModel.ts
js/src/OHLCModel.ts
js/src/PieModel.ts

Fix update_domains and update_data overwrites. Although we should use camelCase in the base Mark class at some point.

Fix update_domains and update_data

---

js/shaders/scatter-fragment.glsl
js/shaders/scatter-vertex.glsl
js/src/ScatterGL.ts

- Remove unused shader chunks
- Remove double "return" statements
- Make render async

Couple of cleans in ScatterGL

---

js/src/AxisModel.ts
js/src/BarsModel.ts
js/src/BoxplotModel.ts
js/src/GraphModel.ts
js/src/GridHeatMapModel.ts
js/src/HeatMapModel.ts
js/src/HistModel.ts
js/src/ImageModel.ts
js/src/LabelModel.ts
js/src/LinesModel.ts
js/src/MarkModel.ts
js/src/MarketMapModel.ts
js/src/OHLCModel.ts
js/src/PieModel.ts
js/src/ScatterBaseModel.ts
js/src/ScatterGLModel.ts
js/src/ScatterModel.ts
js/src/SelectorModel.ts
js/src/index.ts
js/src/serialize.ts
js/src/test/binary_serialization.ts

This will be helpful for bqplot-gl

Export binary array serializer

---

.github/workflows/build.yml

GitHub Actions: Discover typos with codespell

---

docs/environment.yml
docs/source/conf.py
docs/source/usage.rst

cc. @kaiayoung @ChakriCherukuri @ibdafna 
https://user-images.githubusercontent.com/21197331/146786698-690174dd-5ef8-40f5-8b9c-b93971d03559.mp4
We would need Thebe to support Pyolite as a kernel for having in-browser execution, but that's a start :)

Make docs executable

---

setup.py

This is only to fix the github dependents check

Add project name to setup.py

---

.github/workflows/update_galata_references.yaml

Try fixing galata bot permissions

---

.github/workflows/update_galata_references.yaml

This is another attempt of fixing the galata bot

CI: Pass token to checkout

---

.github/workflows/update_galata_references.yaml

Try fixing bot permissions

---

.github/workflows/update_galata_references.yaml

As suggested by [blink1073](https://github.com/blink1073) in https://github.com/jupyterlab/maintainer-tools/pull/41

Try setting up the remote using https

---

.github/workflows/update_galata_references.yaml

Galata bot update push ref

---

.github/workflows/update_galata_references.yaml

Yet another try to fix the Galata bot permissions

---

.github/workflows/build.yml
js/package.json
js/webpack.config.js
js/webpack.lab.config.js

Backport PR #1440: Fix CI

---

js/package.json
js/yarn.lock
setup.cfg

Follow up of https://github.com/bqplot/bqplot/pull/1514
We don't need to require ipywidgets 8, 7 still works

Fix ipywidgets 8 dependency

---

js/src/Figure.ts

Similar approach to what we do in ipyleaflet for supporting both ipywidgets 7 and 8

Fix processPhosphorMessage for ipywidgets 7

---

js/src/Figure.ts
js/src/Mark.ts
js/src/MarketMap.ts
js/src/utils.ts
js/yarn.lock

The `luminoWidget` accessor does not work undo ipywidgets 7

Fix luminowidget

---

mkdocs.yml

fixed doc homepage link and added navigation tabs

---

docs/usage/object-model.md
docs/usage/pyplot.md
docs/usage/updating-plots.md

added docs for usage section (pyplot and object-model)

---

custom_theme/404.html
mkdocs.yml

docs 404 page

---

docs/usage/figure.md

fixed typo flagged by codespell

---

mkdocs.yml

Missing site_url config

---

docs/index.md
docs/installation.md
docs/usage/figure.md
docs/usage/object-model.md
mkdocs.yml

1. Using relative links for navigation
2. Misc cleanup

Mkdocs cleanup

---

docs/api/tooltip.md
docs/usage/updating-plots.md
mkdocs.yml

Mkdocs misc

---

js/src/Figure.ts

Backport PR #1539: fix: figure is not updating when margins change

---

.github/workflows/build.yml
.github/workflows/update_galata_references.yaml
setup.cfg

Bump pandas maxversion to v2 and see how badly things break.
* #1586
See diff.
N/A
N/A

EXP: Bump pandas maxversion to v2

---

.github/workflows/build.yml
test-environment.yml
ui-tests/tests/bqplot.test.ts

CI: Installation verbose

---

.github/workflows/update_galata_references.yaml

Update galata bot for using with JupyterLab 4

---

js/src/ScatterGL.ts
js/src/test/scatter-mega.ts

Fixes #1661 
We may have to port this to bqplot_gl?

Fix dynamic range for ScatterGL
