bqplot/traits.py

This is a quick fix to the date conversion issue that occurs when resetting scales...

None cannot be converted to a datetime

---

README.md

The current method gives me this:
```bash
$ git clone git@github.com:bloomberg/bqplot.git
Cloning into 'bqplot'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

Use a secure address for cloning

---

setup.py

Previously, bdist_egg would build the manifest before getting the js files, so it would leave the js files out. This affected the conda install, for example.  This commit ensures that the js files are always retrieved before building the manifest.

Get the bower js files before building the egg info

---

bqplot/nbextension/OHLC.js

I took out the old commented-out code that I wrote. I figured I would explain what it does here so that you do not feel guilty removing it.
A picture is worth 1,000 words, so take a look:
Currently, the selection must be covering the centre of the mark in order for it to be highlighted. You can see that in this picture, the mark to the left of the cursor is not highlighted.
The old code would cause the mark to the left of the cursor to be highlighted because the selection is hitting its tail. Like this:
Side note: I moved some variables around so they were closer to the context they were being used in.

Cleaned up old commented-out code in OHLC.js

---

bqplot/nbextension/Axis.js
bqplot/nbextension/Bars.js
bqplot/nbextension/ColorAxis.js
bqplot/nbextension/Figure.js
bqplot/nbextension/GridHeatMap.js
bqplot/nbextension/Hist.js
bqplot/nbextension/Lines.js
bqplot/nbextension/Map.js
bqplot/nbextension/MarketMap.js
bqplot/nbextension/OHLC.js
bqplot/nbextension/Pie.js
bqplot/nbextension/Scatter.js

Remove calls to deprecated `widget.after_displayed`

---

examples/Market Map.ipynb
examples/Pie.ipynb

- Use the country full name as title in the chart for the MarketMap example
- better default radius in Pie example.

Use country name as chart title in example.

---

bqplot/figure.py
bqplot/marks.py
bqplot/nbextension/Axis.js
bqplot/nbextension/Bars.js
bqplot/nbextension/FlexLine.js
bqplot/nbextension/Hist.js
bqplot/nbextension/Lines.js
bqplot/nbextension/Pie.js
bqplot/nbextension/PieModel.js
bqplot/nbextension/Scatter.js
examples/Animations.ipynb
examples/Axis Properties.ipynb
examples/Candles.ipynb
examples/Lines.ipynb
examples/Pie.ipynb
examples/Scatter.ipynb

1. Moved animate_dur attribute from marks to figure. Since figure contains axis and multiple marks it makes sense for all of them to transition together.
2. Updated the example notebooks to reflect the above change
3. Fixed couple of bugs in Pie mark
4. Added a custom tween for Pie transitions
Note: Axis gridlines and ticks should also transition when individual marks transition. I am working on it and will create a separate PR for that.

Moved animate_dur attribute from marks to figure

---

bqplot/marks.py
bqplot/nbextension/GridHeatMap.js
bqplot/nbextension/Pie.js
examples/GridHeatMap.ipynb

This PR enables a click interaction for selection on the GridHeatMap. The selection works as in other marks but mimics Excel in that, the `ctrl` key allows additional selection, while the `Shift` key selects the entire range from the last selected cell to the current clicked cell.
The range selection allows arbitrary ranges to be selected with the `Shift` key. 
The `grid_map.selected` trait returns a list of list containing the row index and the column index of each selected cell.

First pass at Selection on GridHeatMap

---

bqplot/marks.py
bqplot/nbextension/Lines.js
examples/Lines.ipynb

Added area chart functionalities to the `Lines` mark
* `fill` controls what area to fill
* `none` is the default no-fill
* `top`, `bottom` fills to the plot area upper and lower limits
* `inside` is the previous behavior for filling, it closes the path and fills it in
* `fill_colors` and `fill_opacities` control the styling of the filling, they work as `opacities` and `colors` currently do
* If no `fill_colors` is provided, the fill color defaults to the corresponding line's color.

Area Chart

---

bqplot/nbextension/bqplot.less

There is no need to specify the white background color in the case of the light theme, especially with the new multiple selection feature of notebook 4.1.

No need to specify background color

---

setup.py

In our installation, bower was not on the path and the installation quietly failed.  With the exception, it should stop.

setup.py: fail with exception when bower cannot be found.

---

examples/Market Map.ipynb

When running the kernel in the Chromium sandbox, filesystem access with
relative paths is rejected.

examples: Use absolute paths for accessing the file system

---

bqplot/nbextension/PanZoom.js

This change is necessary for embedding bqplot figures in web pages.

Missing underscore in PanZoom

---

bqplot/axes.py
bqplot/default_tooltip.py
bqplot/figure.py
bqplot/interacts.py
bqplot/market_map.py
bqplot/marks.py
bqplot/pyplot.py
bqplot/scales.py
bqplot/toolbar.py

Migration to the new traitlets API: use `.tag` to specify metadata.

Use .tag to specify metadata

---

bqplot/nbextension/Figure.js

IE11 does not support classList for svg elements.

IE11 support

---

bqplot/nbextension/BarsModel.js
bqplot/nbextension/BoxplotModel.js
bqplot/nbextension/GridHeatMapModel.js
bqplot/nbextension/HistModel.js
bqplot/nbextension/LinesModel.js
bqplot/nbextension/MapModel.js
bqplot/nbextension/MarkModel.js
bqplot/nbextension/OHLCModel.js
bqplot/nbextension/PieModel.js
bqplot/nbextension/ScatterModel.js

There was an issue with scales in the same mark being used for different attributes. Suppose the same scale is used for `x` and `y`, then the last attribute to be set gets control of the domain as the key in the dictionary was the mark model id. 
Adding the attribute as a suffix to the key so that it does not over write values set by other attributes.

scales domain setting bug fix

---

bqplot/marks.py
bqplot/nbextension/Axis.js
bqplot/nbextension/FlexLine.js
bqplot/nbextension/HistModel.js
bqplot/nbextension/LinearColorScaleModel.js
bqplot/nbextension/Mark.js
bqplot/nbextension/MarketMap.js
bqplot/traits.py
examples/Hist.ipynb

Fixed the following bugs:
Positioning of tooltip when scrolling horizontally.
`MarketMap` colors are not applied on initial draw.
`LinearColorScale` `mid` attribute not updating.
`ColorAxis` auto tick format not working.
Tooltip is blocking mouse events after it is invisible.
`FlexLine` update of  the domain of the scales for `x`, `y` and `color` were failing.
Added the ability to output normalized data in a `Histogram` so that it can be used to compare different Histograms.

Various bug fixes

---

examples/Scatter.ipynb

Thanks to Sally Wilsak for pointing this out.

fix typo in notebook: "removing"

---

examples/Map.ipynb

@SylvainCorlay `topo_load` already has the WorldMap as its default. It isn't needed anymore. I removed it and renormalized the chloropleth a bit better.
Changed the `import *` syntax as well

Change Map Example notebook

---

bqplot/marks.py
examples/Map.ipynb
js/src/Map.js

@SylvainCorlay @ssunkara1 @jasongrout Regarding #40. This is a major API change.
Map now takes a `Dict` for its `colors` attribute, so the `id` can be passed to it. It looks for a key `default_value` in the dict for the default value.
```python
sc_geo = Mercator()
x = Map(map_data=topo_load('WorldMapData.json'), scales={'projection': sc_geo}, 
colors={682: 'Green', 356: 'Red', 643: '#0000ff',
'default_color': 'DarkOrange'})
fig = Figure(marks=[x], fig_color='deepskyblue', title='Advanced Map Example')
display(fig)
```
replaces
```python
sc_geo = Mercator()
x = Map(map_data=topo_load('WorldMapData.json'), scales={'projection': sc_geo}, 
default_color='Green')
fig = Figure(marks=[x], fig_color='deepskyblue', title='Advanced Map Example')
display(fig)
```

Make Map default color a Dict

---

bqplot/marks.py
examples/Scatter.ipynb
js/src/Scatter.js

This pull request adds two more callbacks to Scatter, namely the `on_drag_start` which is called when a point triggers a d3 `dragstart` event and `on_drag` which is called while a point is being dragged.
Unfortunately, it seems, for `dragstart` and `dragend` the current position of the `Scatter` point cannot be known. If they can, a similar template for `drag` can be followed.
@ssunkara1 @SylvainCorlay

Add callbacks for all drag behavior in Scatter

---

bqplot/marks.py
examples/Pie.ipynb
js/src/Pie.js

Added the following options:
- `display_labels`: whether to make the labels visible or not
- `label_color`
- `font_size`
- `font_weight`
Fixes issue #99, helps with #130

Styling options for pie labels

---

examples/Mark Interactions.ipynb
js/src/Scatter.js

@ssunkara1 @ChakriCherukuri @rmenegaux This is regarding #154.
Should we have the `shift` key functionality for `Scatter` as well? It doesnt seem to make sense to me, since inherently there's no connection between the points index and its x-coordinate, should the shift move in x or y coordinates then?

Add selection for click in Scatter Chart interactions

---

js/src/Scatter.js

This does several things:
- fixes issue #59 
- elements listen to drag events only if `enable_move` is true
- does not recompute `x` (resp. `y`) if `restrict_x` (resp. `restrict_y`) is true
- the `point` value in the custom message for `on_drag` is now adapted to `restrict_x` and `restrict_y`
(it previously returned the mouse position, regardless of whether they were true or not)
- after the drag, dot size and color reset to their initial value rather than the default one (this wasn't too problematic because usually the drag triggers a redraw anyway, but if the point doesn't move and there is no redraw, then its size/color becomes off)

Fixes in Scatter drag

---

js/src/Lines.js

Points with infinite `y` will not be drawn.
This addresses issue #91

handle infinite values in Lines

---

README.md

Given the traffic on the bqplot chat, I would rather consolidate everything on the ipywidgets chat.

Change link to ipython/ipywidgets

---

bqplot/figure.py
examples/Basic Plotting.ipynb
js/src/Figure.js

@SylvainCorlay Brought back the save_png function for the `Figure`, @stonebig asked for a stable beta, I think this should probably be included

Reinstated save_png method of figure

---

js/src/Figure.js

In update_layout this change will explicitly use min_height
and min_width for the viewport.

Figure SVG size based on min width and height

---

bqplot/pyplot.py
bqplot/scales.py

Added a class level attribute called `preference_order` for Scales. If two scales have the same range and domain type, then the scale automatically selected by pyplot is based on the value of the new attribute.

pyplot adding order for compatible scales

---

README.md

@SylvainCorlay @rmenegaux This change is because none of the examples or talks ever use bq. This is pretty much the only place. I guess it needs to be changed.
I also added a title.

Change README.md to remove bq. imports

---

js/src/Axis.js
js/src/bqplot.less

@bloomberg/bqplot-developers I updated the `theme-light` `Figure` background  because the grey is a bit too contrasting to something closer to white.
What other changes can we think of? Maybe crisper axes?

Update Light Theme

---

js/src/Lines.js

The curves should not be indexed by their labels since we do not impose a one-to-one mapping between them.
This fixes issue #129
It will also make the legend display properly in case there are identical labels.

remove indexing by label in Lines.js

---

js/src/Lines.js
js/src/LinesModel.js

This does two things:
- Separates the creation of the labels and their positioning. The label positions update correctly now, including with panning and zooming.
- Adds a listener to a change in the `labels` trait, that correctly updates the inline labels.
Also updates the d3 bound data of the elements, to keep the names consistent.

line labels move with the line

---

bqplot/interacts.py
bqplot/marks.py
bqplot/pyplot.py
js/src/Toolbar.js

- the `panzoom` python helper function uses scales corresponding to a given dimension.
- toolbar widget does the same thing.
- we filter with the `preserve_domain` attribute.
- `vline` and `hline` now return the mark like other drawing routines in pyplot.
This fixes #220 .

pyplot fixes

---

setup.py

the `check_call` command works only for .exe files. .cmd files are not found by that unless the additional argument is passed and npm is not a .exe file. 
I checked that this works on windows and Ubuntu. Have not checked it on a mac.

fixing setup.py for windows

---

js/src/LinearScaleModel.js

When no data is provided, update_reverse is always applied. This PR fixes this problem.

Bug fix in update_reverse

---

bqplot/pyplot.py

@ssunkara1 @SylvainCorlay Having to call plt.current_figure() everytime doesn't make sense. I return the _context['figure']
#235 
Also fixes #229

Return pyplot figure

---

js/src/bqplot.less

The color is the same as the one of the rendered markdown and button captions.

Lighter tick marks

---

js/src/ColorScaleModel.js
js/src/DateScaleModel.js
js/src/LinearScaleModel.js
js/src/LogScaleModel.js
js/src/OrdinalScaleModel.js
js/src/ScaleModel.js

This is fixing an issue introduced in #237. 
With the previous change, if we update `reverse` from `True` to `False` nothing happens. Since the function was being called whenever `reverse` is changed, I think the logic of the function is fine.
With regards to the issue that @jmabille was facing, I ran into the issue before but I cannot reproduce it now. I think the issue (@jmabille correct me if I am wrong) was that when no data is passed to the `DateScale`, the default domain of the scale is from `[today, epoch date (1970, 1, 1)]`. That issue is slightly different and does not have much to do with the `reverse`. 
I marked the PR as WIP as I want the issue @jmabille faced to be fixed as part of this.

Bug fix with domain reverse

---

bqplot/market_map.py
examples/Marks/Market Map.ipynb
js/src/MarketMap.js
js/src/MarketMapModel.js

@ssunkara1 This adds a `font_style` and `title` attribute. Also, with the new `ipywidgets` you need to unpack the layout, so that the `model.state_change` isn't `undefined`.(see #255). I can also move the `update_data` to the model in this PR if you like but me and @vedantam probably need the font/title.
Also, the notebook was buggy since `ipywidgets` was imported before `from bqplot import *` which means that `bqplot`'s `Label` was being used rather than the `ipywidgets` one

Market Map title, font and bug fix

---

js/src/MarketMap.js

Right now, if there are more than 1 MarketMaps in the same notebook, changing the `font_style` for any one of the MarketMaps, changes the style for all of the MarketMaps.

Minor bug fix in Market Map font styles

---

bqplot/traits.py

There was a bug in `PandasDataFrame` trait where we were assuming that the index is not named. This PR fixes that issue. Because of this, we were getting the issue in `MarketMap` when we click on the cell.
There is another reason why this issue surfaced only now. Previously in `ipywidgets`, only attributes whose value changed were sent across to the python side on call of `.touch` function. But now, in the first and second calls, many more attributes are sent across. @jasongrout is looking at the issue on the `ipywidgets` side.

Fixing issue with Pandas data frame trait

---

bqplot/market_map.py
bqplot/traits.py
examples/Marks/Market Map.ipynb
examples/Marks/Scatter.ipynb

Previously we were passing `() or `(0,)` as args to the constructor of `NdArray` and `PandaDataFrame` traits which was setting the default value. 
Also includes a bug fix for `_from_json` of `PandasDataFrame` trait.

Bug fixes for default values

---

bqplot/marks.py

The default value of the principal data traits of marks (`x` and `y` for Lines) is `None`, even though they do not allow `None`.
We should be able to first create the Mark instance, and then set the data attributes programmatically.
This depends on #291

Set default data attributes of marks to []

---

examples/Advanced Plotting/Advanced Plotting.ipynb
examples/Advanced Plotting/Animations.ipynb
examples/Advanced Plotting/Axis Properties.ipynb
examples/Advanced Plotting/Plotting Dates.ipynb
examples/Basic Plotting/Basic Plotting.ipynb
examples/Interactions/Interaction Layer.ipynb
examples/Interactions/Mark Interactions.ipynb
examples/Introduction.ipynb
examples/Marks/Bars.ipynb
examples/Marks/Boxplot.ipynb
examples/Marks/Candles.ipynb
examples/Marks/FlexLine.ipynb
examples/Marks/GridHeatMap.ipynb
examples/Marks/Hist.ipynb
examples/Marks/Label.ipynb
examples/Marks/Lines.ipynb
examples/Marks/Map.ipynb
examples/Marks/Market Map.ipynb
examples/Marks/Pie.ipynb
examples/Marks/Scatter.ipynb

This removes all the uses of `IPython.display.display` and only uses the displaying of the last computed value as it was suggested by Fernando.

Remove uses of IPython.display.display

---

js/src/Figure.js
js/src/bqplot.less

In the transition to native DOM api calls, the front `-` went missing. Moving this to the css, and adding a rule for the cursor.

Disable user select and set default cursor on axis ticks

---

bqplot/interacts.py
bqplot/marks.py

The bug fix on the Union metadata in traitlets upstream requires this change. When traitlets 4.3 is released, I will remove the individual `sync=True` on the components of the Union.

Union-level metadata

---

js/src/ColorUtils.js

@ssunkara1 @SylvainCorlay This is a temporary fix, but the ColorUtils needs to be refactored to not depend on an arbitrary index like `21`

Add Blues to Color Schemes

---

bqplot/marks.py
js/src/Label.js
js/src/LabelModel.js
js/src/Scatter.js
js/src/ScatterModel.js

@ssunkara1 @SylvainCorlay Useful for different kinds of `Scatter`/`Label`
@rmenegaux There seems to be an issue with the `Label` drag, related to the `align` attribute.

Add drag_size attribute to objects

---

js/src/Mark.js

We can't clear `this.scales` in `Mark` view before the promise callback because changes to other traits can happen before the promise is resolved, mark views will throw an error. (We assume `this.scales` is always set)

Fixing race condition

---

bqplot/scales.py
js/src/LinearScaleModel.js
js/src/MarkModel.js

As of now, unless a `min` and `max` is set, the domain of the scale is tied to the range of the data. This is what we want for static views, but in some cases we want to visualize the change in data-range. The `StabilizedScale` selectively updates its domain, changing it only when the range of the data becomes too small or too big (user-defined thresholds). 
How it works
---------------
- Initially, on the first draw and on each reset, the data spans a proportion `mid_range` (80% by default) of the total space.
- This domain is kept on change of the data, unless the new data range is more than 100%, or less than `min_range` (60% by default) of the current domain. In that case, the scale domain is reset. 
If either `min_range` or `mid_range` is changed from the back-end, the domain is …

Stabilized Scale

---

bqplot/interacts.py

The `selected` attribute for `selectors` can be set from the python side. The docs state it as read-only by mistake.

Minor fix in docs for selectors

---

examples/Marks/Map.ipynb
js/src/Map.js
js/src/MapModel.js

@SylvainCorlay This allows arbitrary GeoJSON or TopoJSON files to be taken by the map, allowing layered visuals like:
WIP because I need to find or make a proper capitals GeoJSON file, and add it to the LICENSE. Feel free to review the code otherwise.

Allow arbitrary GeoJSON or TopoJSON files for map data

---

bqplot/marks.py

The interpolation options that provide step graphs are already provided by d3, but just not exposed in bqplot.

Add interpolation options for steps-before and steps-after

---

bqplot/pyplot.py

For a 2-d `y` the default `x` is not correct. This is because, for two-d arrays, the len function gives shape[0]. But for `Lines`, `shape[0]` is the number of lines and `shape[1]` is the number of points in each line.

fixing default x for pyplot.plot

---

bqplot/pyplot.py

The `fig` kwarg in `hline` and `vline` was superfluous, since they call `plot` which already has a `figure` kwarg.

Remove the `fig` kwarg in hline and vline

---

bqplot/pyplot.py
examples/Basic Plotting/Pyplot.ipynb

@madridnick @ssunkara1 Added support for a data argument ala matplotlib.
Currently it works only for the args (not the kwargs) of the plotting functions and follows matplotlib in that it assumes whatever names you pass it is supported by the _get_item of your data.
```
plt.figure()
plt.plot('Security 1', 'Security 2', data=price_data)
plt.show()
```

Add a data attribute to pyplot's plot functions

---

examples/Interactions/Mark Interactions.ipynb
examples/Marks/Market Map.ipynb
js/src/Figure.js
js/src/Mark.js

If we trigger `displayed` on the `view` before the `widget` in the `tooltip` is displayed, the `width` and `height` are set to negative values as the `el.clientHeight` and `el.clientWidth` are 0. 
This PR fixes it by not triggering `displayed` when `tooltip` is not necessarily displayed.

Tooltip figure bug fix

---

js/src/MarketMap.js

Right now, `MarketMap` does not display if the argument `ref_data` is not passed because of a JS error. This fixes that bug.

Market map refdata fix

---

bqplot/market_map.py
js/src/MarketMap.js

There is an issue with hovering over the `MarketMap` when `hovered_stroke` is present. There is a dummy hover event which is triggered because of the addition of the hovered rectangle. Fixing that issue and also making `selected_stroke` and `hovered_stroke` nullable (Don't think this is a word).

Hover issue for market map

---

js/src/MarketMap.js

Triggering `displayed` so that the size of the `Figure` is set.

Figure as a tooltip for MarketMap doesn't display

---

js/src/GridHeatMap.js

When `selected` attribute was being set to `None` from the Python side, there was a JS error because of a missing null check. Also, clearing out the `anchor_style` and applying default style on the cells when selection is reset.

GridHeatmap minor issues fix

---

js/src/Figure.js
js/src/bqplot.less

This time, we had issues with the intrinsic aspect ratio from the view box messing up the calculated width and height. Setting the view box to ‘0 0 1 1’ and then measuring the width/height meant that it would try to expand to a 1:1 aspect ratio and then calculate the hard minimum sizes and set them, often leading to plots that would overflow their containing box.
Thanks to @ssunkara1 for working on this commit as well.

Yet again tackling resizing, this time letting flex box do the hard work

---

bqplot/figure.py
js/src/Figure.js
js/src/FigureModel.js
js/src/bqplot.less

Thanks @SylvainCorlay for the logic.

Set a natural width/height of 640x480. Don’t expand by default.

---

bqplot/figure.py

We might often have multiple bqplot charts stacked on a 16:9 monitor. This increases the max aspect ratio to fill the space on a 16:9 monitor when we have about 3 charts stacked on top of each other.

Increase max aspect ratio

---

js/src/Mark.js
js/src/MarkModel.js
js/src/ScatterBase.js

A couple of points here.
1. We have to clear the `hovered_style` and `unhovered_style` as well because if they set styles which are not overridden by the `set_default_style` they will remain on the elements.
2. When `hovered_index` is set to `null`, we do not want it to be set to a list which puts off the calculation of the `unhovered_indices`.

Clearing hovered style

---

js/src/Figure.js

append is only implemented in some of the latest browsers, so causes errors in, for example, Chrome before version 54.

DOM append -> appendChild

---

js/src/ScatterBaseModel.js

This was forgotten, and causing the pyplot PanZoom to fail when a rotation scale was specified.

Adding rotation to scatter scales metadata

---

js/src/Lines.js

When the `marrker` of `Lines` is set to `None` nothing happens as of now.
Also, there is a bigger issue which is not solved here. When a JS exception occurs, all the handlers attached through `on_some_change` do not work any more. That is causing a bug when `marker` is set to `None` because, the `Lines` object does not listen to change in `x`, `y`. etc anymore.

Marker change issue for Lines

---

js/src/Scatter.js
js/src/ScatterBase.js

The positioning of Scatter labels was done according to the default_size, and not the actual size of the points (it did not adjust when there was a size scale involved).

Adjust offset of scatter labels

---

js/src/OrdinalScale.js

The following code results in the marks not rendering randomly (as of ipywidgets 6.0, bqplot 0.9beta)
```python
import bqplot
mean0, cov0, size0 = [-1.0, -1.0], [[1.0, -0.4], [-0.4, 1.0]], 10
mean1, cov1, size1 = [ 1.0,  1.0], [[1.0,  0.4], [ 0.4, 1.0]], 5
sample = np.vstack([
np.random.multivariate_normal(mean0, cov0, size0),
np.random.multivariate_normal(mean1, cov1, size1)
])
category = np.hstack([np.ones(size0), -np.ones(size1)])
plt.figure()
plt.scatter(sample[:, 0], sample[:, 1], color=category, scales={
'color': bqplot.OrdinalColorScale()
}, enable_move=True)
plt.show()
```
However, width a linear color scale, there is no such issue.
The problem seems to come from the forced call of "update_domain" of the `OrdinalColorScale`, which is …

Fix race condition with ordinal scale

---

js/src/Axis.js
js/src/Bars.js
js/src/FlexLine.js
js/src/Hist.js
js/src/Label.js
js/src/Lines.js
js/src/Map.js
js/src/Mark.js
js/src/MarketMap.js
js/src/Pie.js
js/src/Scatter.js
js/src/ScatterBase.js

Added a name to each transition. The convention I followed was to add the name of the  function which contains the transition. In this way, transitions started by other functions are not interrupted. Luckily, we do not have more than 1 transition on the same selection in the same function :)
Fixes #456.

Fixing transitions

---

js/src/Axis.js

Currently, when `tick_values` are set to an array and `num_ticks` is not set, there are no ticks displayed. This can be seen in the `Advanced Plotting.ipynb` example.

Axis tick values issue fix

---

js/src/Figure.js

I noticed the Mark's `remove` method was not called, this fixes that, and I think the same for axis. As discussed with @jasongrout

remove marks and axis

---

examples/Applications/Outlier Detection.ipynb

`pandas.tseries.index` is only in pandas version `0.20.2`. Directly importing `DatetimeIndex` from `pandas` removes that explicit dependency.

pandas version dependency fix in DNA example

---

bqplot/figure.py

At the request of @ssunkara1, this addresses an omission in the fix in #488.

Fix bqplot.Figure documentation typo

---

bqplot/pyplot.py

Two issues are fixed here:
1. With the decorator, documentation of `pyplot.plot` etc does not show up when we run `help(plt.plot)` etc. 2. When we are plotting a data frame using `pyplot`, if only one argument is passed to `plt.plot`, plotting the index as the default `x`.

Pyplot fixes for documentation pass through and default plotting 

---

js/src/Bars.js

This fixes issue #508 
Extra bars (when the number of rows in `y` decreases) were not being removed in a redraw

Removing extra bars on redraw

---

js/src/BarsModel.js
js/src/BoxplotModel.js
js/src/Figure.js
js/src/GraphModel.js
js/src/GridHeatMap.js
js/src/GridHeatMapModel.js
js/src/HandDraw.js
js/src/HeatMapModel.js
js/src/HistModel.js
js/src/LinesModel.js
js/src/MapModel.js
js/src/MarkModel.js
js/src/MarketMap.js
js/src/OHLCModel.js
js/src/PieModel.js
js/src/ScatterBaseModel.js
js/src/Selector.js

@jasongrout  Because of a change in `ipywidgets' WidgeModel` (https://github.com/jupyter-widgets/ipywidgets/pull/1451) there was a bug in `bqplot` since we were relying on the `id` attribute of `WidgetModel`. This also fixes #517. Thanks @mpacer for reporting this.

model id rename bug fix

---

bqplot/interacts.py

Panzoom wasn't working in jupyter lab. The problem was that PanZoomModel was created at the frontend but not registered at the frontend, hence:
```python
[IPKernelApp] ERROR | Exception opening comm with target: jupyter.widget
Traceback (most recent call last):
File "/Users/maartenbreddels/miniconda3/envs/jupytercon7/lib/python3.6/site-packages/ipykernel/comm/manager.py", line 90, in comm_open
f(comm, msg)
File "/Users/maartenbreddels/miniconda3/envs/jupytercon7/lib/python3.6/site-packages/ipywidgets/widgets/widget.py", line 333, in handle_comm_opened
state['_view_name'])
File "/Users/maartenbreddels/miniconda3/envs/jupytercon7/lib/python3.6/site-packages/ipywidgets/widgets/widget.py", line 254, in get
view_modules = model_names[model_name]
KeyError: 'PanZoomModel'
[IPKernelApp] WARNING | …
```

panzoom fix: register it

---

js/src/Lines.js

This fixes issue #522. The `isFinite` function was added to fix #91. Because of directly using `isFinite` we ignore Ordinal values for `y` attribute of `Lines`.
@rmenegaux

Lines Ordinal Scale fix

---

bqplot/marks.py

Fixes issue #544. @ChakriCherukuri can you have a look as I changed the `rtype` of `link_color` and also have a look if the scales for `link_color` and `color` should be the same by default or different.

adding missing attributes to scaled metadata

---

bqplot/axes.py

I had to dive into the js to figure out that it was expecting d3 based date-string formatting. This should be in the docstring. This might make sense in other places too… but I'm not sure the best way to search exhaustively for this kind of change.

clarify what date format is used for date based tick_formats

---

bqplot/figure.py
js/src/Figure.js

It'd be nice to be able to specify what the filename is for saved PNGs.
Background: I made a figure that's affected by dropdowns, and I wanted to add a "save PNG" button that would save a file whose name is determined by the selected dropdown values.
This is somewhat related to #442 but lets the plot creator specify a filename rather than a path.

Add functionality for specifying a filename when saving to PNG

---

bqplot/marks.py
js/src/Image.js
js/src/ImageModel.js
js/src/index.js

Usage
```python
import bqplot
import ipywidgets as widgets
with open("sample.png", 'rb') as f:
data = f.read()
image = widgets.Image(value=data)
scale_x = bqplot.LinearScale(min=-1, max=2)
scale_y = bqplot.LinearScale(min=-0.5, max=2)
image_mark = bqplot.Image(image=image, scales={'x': scale_x, 'y': scale_y})
fig = bqplot.Figure(padding_x=0, padding_y=0)
fig.marks = [image_mark]
fig.axes = [bqplot.Axis(scale=scale_x), bqplot.Axis(scale=scale_y, orientation='vertical')]
fig
```
It uses the widget.Image widget. Maybe it doesn't do all the things, like colorscales and all, but I think this makes a lot possible already.

new: Image mark

---

bqplot/marks.py
js/src/Lines.js
js/src/LinesModel.js

Adresses issue #523 
As it stands now, the last line will have a color that is different from the corresponding area (if there are n lines, there are only n-1 areas). A way around that is to set its opacity to 0, or to set the colors manually.
Any ideas on how to address this? Otherwise the PR is good to merge as is.

Adding fill-between options in Lines

---

bqplot/marks.py
examples/Marks/Bars.ipynb
examples/Marks/Scatter.ipynb

1. Made default color in bar chart same for all bars (steelblue). Currently bar chart defaults to different colors for each bar which is confusing.
2. Consolidated default colors across marks to have same color (steelblue)
3. Cleaned up Scatter and Bars example notebooks
PS: Chose 'steelblue' as default color since it's similar to the first color of CATEGORY10 and also similar to matplotlib's default color.

Defaults fixes

---

bqplot/pyplot.py

@SylvainCorlay @maartenbreddels 
Takes either an `ipywidgets` `Image` (default), a file name, or a byte string:
```python
from ipywidgets import Image
with open('sample.png', 'rb') as f:
image = Image(value=f.read())
plt.figure()
plt.imshow(image)
plt.show()
```
or
```python
plt.imshow('sample.png', format='filename')
```
or
```python
with open('sample.png', 'rb') as f:
plt.imshow(f.read(), format='openfile')
```
What do you think should be the default?
The matplotlib `imshow` takes a matrix as input so ideally we should support that too, although it would very close to what our `heatmap` does.

First pass at imshow

---

.gitignore
js/src/Figure.js

This was causing the figure tooltips to flicker when the plot area found itself over the mouse position.

Set pointer-events to inherit in plot area for use of figures as tooltip

---

bqplot/traits.py

This fixes some of the future warnings with numpy `1.14.0`.

Fixup numpy depreation warning on np.float as second argument to issubdtype

---

bqplot/pyplot.py

- Add the `cmap` keyword argument to the pyplot plotting functions
```python
plt.scatter(x, y, color=color_data, cmap=['yellow',  'red'])
```
or
```python
plt.scatter(x, y, color=color_data, cmap='viridis')
```
- Add `plt.set_cmap` to change the color map a posteriori

Add the cmap attribute to pyplot

---

js/src/ScatterBase.js

The minimum of the range of the size_scale is no zero, which although might be convenient in some cases does not to predictable behaviour. For instance, see below where the min of the scale is set to zero, the Scatter's size equals y, but because of the minimum size of 10 (at the minimum of the domain), goes below zero (as it extrapolates):
Instead, if simply set to zero, it will lead to the expected behaviour:
If a users wants to have a minimum size, this can easily be computed by changing the domain accordingly.

Scatter scale size range should starts at 0

---

.travis.yml

It seems that node 10.0 may have issues installing JupyterLab.

Use LTS node on travis instead of node 10.0

---

bqplot/figure.py
js/src/Figure.js
js/src/FigureModel.js
js/src/bqplot.less

This PR makes three changes related to layout
1. It fixes #641, meaning that if you set the layout of a figure to be e.g. 100%, the figure was not being re-laid out like it was in JupyterLab.
2. ~~It makes the natural width of the Figure 100%. Natural min-width and min-height are 480px.~~
3. Min and max aspect ratio are set to 0 and 100 (an arbitrary large number corresponding to something very oblong because JSON does not support IEEE infinities).
- Item (1) is a bug fix, which was impacting users of the classic notebook.
- Item (3) is a minor change that should not have much impact expect in complicated JupyterLab layouts.
- ~~item (2) is a major change that may change people's layouts in applications. However I like how charts now take up more real estate by default.~~
Screencast of …

Improve classic notebook layout

---

bqplot/figure.py
js/src/Figure.js
js/src/FigureModel.js

Adds a `Figure.save_svg()` method that downloads the `Figure` in SVG format.
Solves #285 and #558

Save figure as SVG

---

bqplot/interacts.py
js/src/BaseModel.js
js/src/BrushSelector.js
js/src/FastIntervalSelector.js
js/src/IndexSelector.js
js/src/SelectorModel.js

This PR makes the views of Selectors synchronize, as well as rendering Selectors when loading the notebook.
To accomodate for potential different types in the x-scale and y-scale of the 2d `BrushSelector`, its `selected` attribute is split into `selected_x` and `selected_y`. `BrushSelector.selected` is still available for backwards compatibility.

Make selectors render on multiple figures, and on notebook loading

---

js/src/Label.js

This fix aligns labels to be in the center of a rectangle (for e.g. in GridHeatMap if we add labels they are not aligned in center)

aligning label to be in the center

---

bqplot/axes.py
js/src/Axis.js
js/src/AxisModel.js

I’ll follow up with a more comprehensive reworking later, but wanted to at least get the main fixes in for now:
- Added `tick_transform` parameter, which allows users to rotate the tick axis labels: 
- `tick_transform = {‘rotate’: -35}`
`tick_style = {'text-anchor': 'end'}`
- Fixed several state management issues that caused the ticks to be redrawn incorrectly if attributes such as `tick_style` are modified after the plot was created.

Add tick_transform parameter

---

js/src/Axis.js

Fix for the noted issue in which the axes will not be redrawn in the correct position if `fig_margin` is changed on the figure. 
@SylvainCorlay

Fix axis transform issue

---

js/src/bqplot.less

This enables the dark theme on JupyterLab:

Do light/dark styling with JupyterLab theming system.

---

bqplot/scales.py
js/src/ColorScale.js
js/src/GridHeatMap.js

Adds an attribute `extrapolation` to deal with values outside of a `ColorScale`'s domain. It can be one of 2 values:
- `constant` (default): values outside of the domain will be mapped to the min_color or max_color.
- `linear` (previous default): Linear extrapolation from the 2 last (and 2 first) values of the `ColorScale`
Collateral fix: `GridHeatMap` now listens to changes in its color scale

ColorScale extrapolation option

---

.travis.yml
js/karma.conf.js
js/package.json
js/shaders/scales.glsl
js/src/Figure.js

This adds support for WebGL based on threejs (although I think we can also support regl). This will be the basis for #661 and #630.
It works by overlaying a canvas on top of the svg (for performance reasons). However, when a screenshot is needed, the canvas is converted to an image and embedded.

WebGL support for bqplot (threejs based)

---

bqplot/figure.py
js/src/Figure.js
js/src/FigureModel.js

by default, it matches what you see on the screen, for instance on a mac with `window.devicePixelRatio == 2` it will give you an image of twice the resolution.

New: scaling up of png images and have a good default for high dpi screens

---

bqplot/traits.py

The unittests should expose this on travis. It fails locally.

Expose/fix python2.7 issue with binary deserialization

---

js/src/Figure.js

The overlay structure needed for the WebGL support was overly complicated, stripped it down to the bare minimum, and two small fixes.

Figure: DOM simplification for overlay pattern and small fixes

---

bqplot/figure.py
js/package-lock.json
js/package.json
js/src/Figure.js
js/src/bqplot-standalone.less
js/src/bqplot.less

Changes the bqplot CSS to use Jupyter Lab environment CSS variables. -cc @jasongrout @ellisonbg
Also adds a `theme` attribute to the `Figure` so that the user can switch themes manually. Current themes are `gg` and `classic`.
In the light jupyter lab theme, this is what `gg` and `classic` look like:
In the dark theme:

CSS variables

---

examples/Marks/Object Model/Lines.ipynb
examples/Marks/Pyplot/Lines.ipynb
js/package-lock.json
js/src/Lines.js

Fixes #747
Also adds an example of an area chart in the Lines example notebook.

Extend fill_opacities to patches

---

js/src/Boxplot.js

The boxplot mark was previously not responding to various state changes (new data, domain changing, etc), as not all of the selections were rebinding the data to the DOM elements. 
Fixes issue in #710, and some issues noted in #698.

Fix boxplot redraw issues

---

js/src/Axis.js

D3's default number of axis ticks often results in x axis tick labels overlapping each other when when displaying date information on a figure with a narrow width. For example, when multiple plots are displayed in a grid using the ipywidgets `GridBox` widget. This PR reduces the number of suggested ticks if the width falls below a specified threshold, and the user did not specify their own number.

Scale number of suggested axis ticks for DateScale

---

js/src/BrushSelector.js

Stop calling `brush_start/move/end` on programmatic brush changes, and just redraw the brush. I can't think of a use case where we would want those events to be triggered. 
Fixes #771

Silence brush events on programmatic changes

---

examples/Index.ipynb

Difference in capitalization results in a 404.

examples: correct link for FlexLine.ipynb

---

bqplot/traits.py
tests/binary_serialization_test.py

Since pandas is using dtype=object for strings, we need to support that again.
This makes the Wealth of Nations work again.

Support arrays with object type if they are all strings

---

js/src/ImageModel.js
js/src/ScatterBaseModel.js

As mentioned in issue #791 , the `Image` mark was broken

Adding serializer for Image x,y

---

js/src/ScatterBase.js
js/src/ScatterBaseModel.js

Removes extra call to color updating when changing `color` data in `Scatter`.
Fixes issue #788

Fix scatter color updating

---

js/src/Bars.js
js/src/BarsModel.js
js/src/Boxplot.js
js/src/Figure.js
js/src/Graph.js
js/src/GridHeatMap.js
js/src/HeatMap.js
js/src/Hist.js
js/src/HistModel.js
js/src/Lines.js
js/src/Map.js
js/src/Mark.js
js/src/MarketMap.js
js/src/PanZoom.js
js/src/Pie.js
js/src/PieModel.js
js/src/ScatterBase.js
js/src/SquareMarketMap.js

This PR moves the `process_interactions` function into `Mark`, in order to reduce code duplication. By calling `Mark.process_interactions` from `__super__`, this does mean that some branches are executed twice - once for the base class, and then overridden in the child, but I think this is acceptable. Most of this overriding is caused by the child class hooking into the click event, which could be removed by using a method overload instead.
I introduced a small helper function in `Mark` which I didn't re-use it in the other mark classes, to test for `value !== null && value !== undefined`. Having spoken with @maartenbreddels, a longer term solution would be to use lodash, but I thought that beyond the scope of this PR.
As well as refactoring this code, there are also some bugfixes which …

Refactor `process_interactions` into the `Mark` base class, and provide bugfixes for new d3.

---

js/src/Figure.js

When doing
```
fig = Figure(...)
fig.interaction = ...
```
It used to follow a different code path compared to:
```
fig = Figure(interaction=...)
```
The former sometimes caused (together with https://github.com/bloomberg/bqplot/pull/754) an Infinity to end up at the yscale of the interaction, and would never be set again, causing NaN's to appear at `selected_y` exposing #751 and/or https://github.com/jupyter-widgets/traittypes/issues/30. 
This fixes it, by following the same code path as the latter example.

Figure: fix 'timing' issue with setting interact

---

js/src/Bars.js

When bar stroke is set to None as `Bars(stroke=None)`, a black outline is still shown. This PR fixes the issue by making sure stroke style set to `"none"`

add ability to disable bar chart stroke outline

---

js/src/Bars.js

when there are too many bars (bar width too small), d3 scale calculates bar width to be zero and doesn't draw any bars. this PR fixes the issue by making sure bar width isn't set below 1.0 during draw.

prevent zero bar width and make sure plot is still drawn when bar width is too small

---

js/package.json

I ran into issues when installing the latest developer version of the Lab extension with:
```
jupyter labextension install js
```
With these changes, I'm able to successfully install it.

Fix package.json for Jupyter Lab extension

---

js/tsconfig.json

We figured in JupyterLab that any supported browser in the last 2 years or so now supports the es2017 emitted javascript (last one to support native async/await was Safari 10.1 in middle 2017).

Typescript target es2015->es2017

---

js/src/Figure.ts
js/src/test/bars.ts
js/src/test/lines.ts
js/src/test/scatter.ts
js/src/test/widget-utils.ts

In 8eb8b163abe9ee6306f6918067e2f36c1caef2ef the typescript target was moved to es2017. Somehow with my local chrome (74.0.3729.157 on osx) this caused `figure.mark_views` not to be undefined in the unittest. The only explaination I can think of is the rules for when promises are resolved have changed with es2017.
The changes from 8eb8b163abe9ee6306f6918067e2f36c1caef2ef did not enter into #661 (mistake with rebasing?) and never triggered failing karma tests. This was fixed in c3a075f33a3fac39e3347da4cd1ba7881e7902d1, however PR #853 did not fail on Travis, this may be explained by chrome headless being older and maybe having different rules for when Promises are resolved.
The first commit solves this by explicitly creating a promise that will be resolved when the mark_views is created, …

Fix testing and enable many tests

---

bqplot/interacts.py

This removes an unused `_view_name` attribute on the `Selector` class and an `is_date` attribute on the `MultiSelector` class.
It also fixes some pep8 issues.

Remove unused attributes in Selectors

---

docs/source/introduction.rst

It seems `bqplot-screencast.gif` was renamed `wealth-of-nations.gif`
but the reference to the filename was not updated here.
See:
- https://github.com/bloomberg/bqplot/search?q=screencast&type=Commits
- https://github.com/bloomberg/bqplot/commits/057c51e6f657b8e78cf3694785ab4b7c3a25c4f5/bqplot-screencast.gif
- https://github.com/bloomberg/bqplot/blob/057c51e6f657b8e78cf3694785ab4b7c3a25c4f5/bqplot-screencast.gif

Fix animation filename in introduction.rst

---

README.md

Updates binder link to use the `0.11.x` branch, as `stable` was deleted.

Update Binder links in README.md

---

js/src/GridHeatMap.js

This is an alternate hacky "fix" (workaround) for #890 that preserves backwards compatibility.

Fix grid heatmaps

---

js/package.json
js/src/Figure.ts
js/src/ScatterGL.ts

This wayt we can load the shaders the same way.  This will allow bqplot to use WebGL within Jupyter lab.
raw-loader <2 was using common-js, so you could simply do:
```
require('raw-loader!../shaders/scales.glsl')
```
To get the shader string.
Jupyter lab uses raw-loader `~2.0.0`, which uses [ES module style](https://github.com/webpack-contrib/raw-loader/pull/69), requiring you to do:
```
require('raw-loader!../shaders/scales.glsl').default
```
@astrofrog solved this by supporting both cases in #859. However, if we upgrade the devDependencies in bqplot to raw-loader 2, we can use the latter case for bundle building and jupyter lab building.
Replaces #859

fix: Upgrade to raw-loader 2 (like jupyter lab)

---

js/src/ColorScaleModel.ts

The object returned by the `scale` function was always the same object, resulting in populating the Date domain with `n_colors` times the same date.

Fix DateColorScale

---

js/src/OrdinalScale.ts

Fixes #871 
Fixes #872 
Notice that an axis with `OrdinalScale` does not add extra ticks when outer padding is set.

Fixed padding in ordinal scale

---

js/src/MarketMap.ts

- Removes duplicated code
- Fixes an issue with market map coloring
Before this fix:
After this fix:

Market map fixes

---

js/src/ScatterBase.ts

Fix scatter plot multi-selection with `ctrl + left click`.
The `selected` attribute being a `Int32Array`, there is no `push` method, so we need to convert it to an Array first.

Fix multiselection in the Scatter plot

---

js/src/Graph.ts
js/src/Mark.ts
js/src/ScatterBase.ts

Fixes #896
There was a collision in method names:
- in `Mark.ts`, the `reset_hover` is supposed to remove the hover event function
- in `ScatterBase.ts` and `Graph.ts` which inherits from `Mark.ts`, the `reset_hover` is supposed to reset the hovered points stored in the model
This PR:
- Puts the `reset_hover` method private in `Mark.ts` in order to prevent overriding it.
- Renames `reset_hover` into `reset_hover_points` in `ScatterBase.ts` and `Graph.ts`
- Removes the unused `reset_interactions` method

Fix reset_hover method name collision

---

js/src/OrdinalScale.ts

Fixes #871 for good.
The new bandwidth was computed with old padding, resulting in wrong bandwith. This is due to the migration d3 v3 -> d3 v5, each call to `scale.rangeBands(r)` should be replaced with `scale.range(r).paddingInner(0).paddingOuter(0)` if `scale` is an ordinal scale for which inner padding and outer padding have already been specified.
cc @martinRenou @SylvainCorlay

Fixed OrdinalScale padding

---

js/src/BrushSelector.ts
js/src/Figure.ts
js/src/test/index.ts
js/src/test/interacts.ts

d3 seems to sometimes give the y-order of event.selection in reverse order, we now also sort the pixel coordinates.
Also, if the selections were empty, it would print out stack traces in the browser console, although this didn't cause an issue, it is not pretty. Tests are added to avoid regression.

fix: brush selectors threw exception with no selection, fixed order of y test

---

js/src/Figure.ts
js/src/MarketMap.ts
js/src/test/figure.ts

Only create WebGL context when needed
The WebGL context is now lazily created. This should postpone this issue: https://github.com/bloomberg/bqplot/issues/856. Because it will then happen only if there are more than ~18 plots that actually need a WebGL context.
The logic is the following:
- if there is no mark that needs a WebGL context, the context is not created
- if a mark needing a WebGL context is added, we create the context
- we never remove the created WebGL context
This PR should also fix #924

Only create WebGL context when needed

---

bqplot/pyplot.py

To avoid issues with voila it is better to also close the vbox when calling pyplot.close:
https://github.com/jupyter-widgets/ipywidgets/issues/2585
https://github.com/voila-dashboards/voila/issues/433

fix: close vbox as well as figure to avoid issues with voila

---

js/less/bqplot.less
js/src/Figure.ts

This PR removes the natural width of `bqplot`, which was `640px` and replaces it with `auto`.
This will make bqplot figures stretch horizontally in flexbox layouts, such as output areas and nested vboxes. People who were trying to obtain that behavior were generally setting `width` to `100%` causing the figure to overflow its container because of margins, and scrollbars to be displayed. With this change, this should not be required anymore.
Before:
After:
cc @kaiayoung @cquah @maartenbreddels @martinRenou @jasongrout

Auto width for bqplot figures

---

js/src/Bars.ts
js/src/Boxplot.ts
js/src/Map.ts
js/src/ScatterBase.ts

During the es6 transition ` ScatterBase.__super__.process_click.apply(this, [interaction]);`  was translated to `super.process_click.apply([interaction]);`, while we actually had to drop the array. This fixes the bug that causes tooltips now to appear on click, and makes the other calls consistent.

fix: call super.process_hover/click consistently and without argument as array

---

bqplot/scales.py
js/src/OrdinalColorScaleModel.ts
js/src/index.ts

*Issue number of the reported bug or feature request: No existing issue on this*
This PR allows plots using OrdinalColorScale to render correctly on the front-end, using default values, without relying on the python backend to mutate OrdinalScaleModel.
Added a OrdinalColorScaleModel.ts file which inherits from OrdinalScaleModel.ts.
Tested using generated static representation of various plots via sphinx
Add any other context about your contribution here.

Fix ordinal color scale

---

js/src/OHLC.ts

Signed-off-by: idafna <idafna@bloomberg.net>
Added event listeners and relevant class names to monitor for tooltips to appear when hovering on OHLC marks.
No unit testing done, but tooltips now appear. 
** Code to test the feature **
```python
import bqplot as bqp
price_data1 = [['2015-01-02 00:00:00', [161.31, 163.31, 161.0, 162.06]],
['2015-01-05 00:00:00', [161.27, 161.27, 159.19, 159.51]],
['2015-01-06 00:00:00', [159.67, 159.96, 155.17, 156.07]],
['2015-01-07 00:00:00', [157.2, 157.2, 154.03, 155.05]],
['2015-01-08 00:00:00', [156.24, 159.044, 155.55, 158.42]],
['2015-01-09 00:00:00', [158.42, 160.34, 157.25, 159.11]],
['2015-01-12 00:00:00', [159.0, 159.25, 155.76, 156.44]],
['2015-01-13 00:00:00', [157.26, 159.97, …
```

add event listeners and classes to render tooltip for OHLC mark

---

js/src/Figure.ts

Closed #758
We now silently ignore any CORS issues when getting the effective CSS for the svg screenshot
I inserted a custom stylesheet in the notebook to reproduce #758 and confirmed this fixes the issue.

fix: avoids CORS error when building css for svg screenshot

---

js/less/bqplot.less

There was no need to use z-index > 0, and it can interfere with other DOM
elements, example:
https://github.com/voila-dashboards/voila-vuetify/issues/24
The WebGL and the main figure DOM element now have `z-index:0`, instead of 1 and 2 respectively. This renders exactly the same, since they are DOM siblings.
Tested in voila-vuetify to confirm it does not overlap anymore, and tested the Scatter notebook to see if all the interactions still work.

fix: use z-index:0 for all layers to not overlap with higher z-index elements

---

js/src/ColorAxis.ts

*fixes: #981*
Render should return a promise, otherwise, the Figure will not wait before sending events, causing the ColorAxis to miss them, which in turn causes a layout issue.
This is a timing issue, which only happens when there are many browser tabs open, or other forms of delay. This cannot be unit tested as it. It is however not observed to occur with this change.

fix: ColorScale can miss events because render does not return a Promise

---

js/src/PanZoom.ts
js/src/test/index.ts
js/src/test/interacts.ts
js/src/test/widget-utils.ts

Fixes #536
The PanZoom widget now does the operations in pixel space, and converts those back to the domain. This allows panning and zooming to work with LogScale. The methods are refactored a bit such that the pan and zoom can be invoked from the unittests.
Panning is tested in linear and log axes by tracking the red color of the single scatter. Zooming is tested by checking that the scale domain is modified.
This came up when moving ipyvolume to use bqplot scales: https://github.com/maartenbreddels/ipyvolume/pull/281
where I was making an example where I can pan for both ipyvolume and bqplot .
screencapture:

fix: make pan and zoom work with Logscale

---

js/src/Figure.ts
js/src/MarketMap.ts

Before this change, the Figure was rendered once with a default size of `640x480` before `this.el` was even attached to the DOM. And there was a resize when the element is actually attached to the page.
After the change, the Figure waits for `this.el` to be attached before doing any rendering, and it renders in the available space specified by the CSS rules (width: auto, height: 480 by default). This prevents doing an extra resize, and it prevents the figure to take a first hardcoded size.

Refactor Figure sizing logic

---

js/src/Figure.ts
js/src/test/index.ts
js/src/test/interacts.ts

From the CSS, I now extract the variables used, get the computed values, and define those css variables in the generated css.
Manually call fig.save_svg and test if the output matches the classical notebook. Maybe a good idea to also test in Lab, with dark mode.

fix: screenshot CSS was missing CSS variables

---

js/src/OHLC.ts

Selection state is now supported for the OHLC mark. 
No unit test, but tested on a Jupyter Notebook using the code below.
** Code to test feature **
```python
from bqplot import *
price_data1 = [['2015-01-02 00:00:00', [161.31, 163.31, 161.0, 162.06]],
['2015-01-05 00:00:00', [161.27, 161.27, 159.19, 159.51]],
['2015-01-06 00:00:00', [159.67, 159.96, 155.17, 156.07]],
['2015-01-07 00:00:00', [157.2, 157.2, 154.03, 155.05]],
['2015-01-08 00:00:00', [156.24, 159.044, 155.55, 158.42]],
['2015-01-09 00:00:00', [158.42, 160.34, 157.25, 159.11]],
['2015-01-12 00:00:00', [159.0, 159.25, 155.76, 156.44]],
['2015-01-13 00:00:00', [157.26, 159.97, 155.68, 156.81]],
['2015-01-14 00:00:00', [154.86, 156.49, 153.74, 155.8]], …
```

Ohlc selections

---

js/src/Figure.ts

Figure.relayout is being called very often (5x at initial display), and unconditionally will do the work (call requestAnimation). These calls can stack up when resizing the window as well, leading to bad performance. We now keep track if the relayout was already requested, and will only schedule a new one when the last one is finished (similar to how we do it with webgl and in ipyvolume).
Tests pass, and tested in notebook. Putting a log statement in relayoutImpl shows 5 prints before, 2 after (so I think we can still improve even more if we want).

performance: avoid calling relayout too often

---

RELEASE.md
bqplot/_version.py
js/package-lock.json
js/package.json

This is the tagged published release commit for bqplot 0.12.3, npm package 0.5.3.
dist/bqplot-0.12.3-py2.py3-none-any.whl
md5: e0829197d0287783f30419a56d210814
sha1: c33cd72452c0035f194293bde5fa855d87d55f51
sha256: b1b9664c4faaae91ec3773b1083bfa97108a4d6556109afed2ebaeab8c5c83b6
dist/bqplot-0.12.3.tar.gz
md5: 78520772cc1aa7770bcf02eaadf81541
sha1: 7e262468ff2189b3de397b86315e63206a213337
sha256: 7292b57694ebe8347e48e16bd47449bbd886f9c2c238b744ed59871960451b59
CC @kaiayoung

bqplot 0.12.3, npm package 0.5.3

---

js/src/Bars.ts
js/src/Boxplot.ts
js/src/BrushSelector.ts
js/src/Hist.ts
js/src/Lines.ts
js/src/OHLC.ts
js/src/Pie.ts
js/src/ScatterBase.ts
js/src/test/interacts.ts

The `Mark.selected` attribute should be a typed array. Although bqplot supports JSON/lists, they will be converted to a numpy array on the kernel side. This will then be seen as a change on the kernel and will be sent back to the frontend. This causes a lot of echoing, causing old selections to be visible in between.
ScatterBase and Hist are tested, the rest follows a similar pattern.
**Unrelated issue**
I also had to change the return value of OHCL, since TypeScript complained. I am not sure this is correct, since I don't understand this method. A review would be wise.

Fix: Mark.selected should be a TypedArray / selection echo

---

js/src/BrushSelector.ts
js/src/ScatterBase.ts

Fix error with `invert` not being a d3's Ordinal scale method

---

js/src/Figure.ts

Fixes #1023
Relayout a figure on the after-show event. Also, optimize a bit by not laying out figures that are known to be invisible (for example, in a background tab or accordion slot.
```python
from ipywidgets import Tab
from bqplot import pyplot as plt
f=plt.figure()
plt.plot([1,2,3], [1,2,3])
g=plt.figure()
plt.plot([3,2,1], [1,2,3])
Tab(children=[f, g])
```
Currently the plot in the non-active tab is rendered in a minimal size and not updated. This updates that plot when it is shown by activating a tab. This also optimizes a bit by not redrawing the figures in non-active tabs as the frame is resized.
This is an alternative fix to https://github.com/bloomberg/bqplot/pull/1029. It is not as fancy (i.e., it doesn't …

Relayout figures after show events.

---

js/package.json

I think this is all that is needed to get bqplot to work in JupyterLab 2.0 while still having it work in JupyterLab 1.x.
Notice that I added some phosphor dependencies, which are needed (we are importing from phosphor, but didn't list phosphor as a dependency).
Is there a reason for not having `@jupyter-widgets/base@^1` as a dependency, just curious? In other words, a version of `^1 || ^2 || ^3`?

Update to work in JupyterLab 2.0

---

js/less/bqplot.less

This will give a default size to the figure when added in a tooltip. The size used is 2/3 of the old natural size, which was 640/480

Add default sizing for a figure in tooltip

---

js/src/HandDraw.ts

*Issue number of the reported bug or feature request: #971*
This ensures that the function used to select the correct `lines_view` curve in the HandDraw interactor has access to the collection of lines_view objects.
I verified that prior to this, the handdraw example (in #971) did not work, and that subsequent to it, it did.
During the first click on a curve with this interactor, the line updates as the click is in-progress.  Subsequent clicks have the line disappear between mousedown and mouseup.

Bind handdraw attr() function to "this"

---

bqplot/marks.py
js/less/bqplot.less
js/src/Image.ts
js/src/ImageModel.ts

I'd opened an old PR for this, which I've now closed.
This PR adds the ability to enable pixellation for an image. This is useful when using an Image display as a heatmap, as it is more performant than the builtin heatmap.

Add image pixelation control

---

js/src/Mark.ts
js/src/MarkModel.ts
js/src/OHLC.ts
js/src/OHLCModel.ts

I'd opened another PR which I have now closed:
The `display_el_classes` attribute is used by `Mark` to determine whether the mark responds to hit tests (see https://github.com/agoose77/bqplot/blob/cc37ac78cd80e6a91a66f615493c605ed3ae9feb/js/src/Mark.ts#L512). Before the TS port was performed, some of these attributes were erroneously defined on the Model *instead* of the Mark.

Move attributes from model to mark

---

js/src/Figure.ts

Depending on timing, Figure.debouncedRelayout was sometimes undefined, so we just have to assign this earlier.

fix: Figure.debouncedRelayout could be undefined

---

examples/Applications/Wealth of Nations.ipynb

This makes it clearer the x scale is a log scale.

Make wealth of nations ticks a bit nicer

---

js/src/BrushSelector.ts
js/src/Figure.ts
js/src/test/interacts.ts

*Issue number of the reported bug or feature request: #1067*
BrushSelector.relayout was doing too much, a part is split off into the method `syncModelToBrush`, which is now called in render and in selected_changed (which is called when the selected_x/y properties change).
Also, render is made async, and modernized, so that it's only attached to the DOM after the scales are created. This also makes the unittests much cleaner.
Full unittestst included, which tests if the rectangle (green) is drawn (pixel color is tested).

fix: brush DOM state was not always in sync with model

---

js/src/BrushSelector.ts

Fixes #1085
Caused by #1069 ffaecc2589f9ba18f06ed7596a0be072f79a0f1e
I removed the call to this.d3el.call(this.brush); because it gave strange results.
The 'strange' results were actually caused by calling extend, instead of move.
Look a bit of time because we did not have #1096

fix: redraw the d3-brush when the domain/screen changes

---

js/src/LinearScale.ts

I was trying to debug #1085 which led me down a long rabbit hole, because the scale passed to the Scatter was not the same scale that was passed to the Interaction (a common error). This causes `model.domain` to be an empty list, causing this unpadded_scale to have a domain of NaN,NaN. This leads to weird behaviour, so I think the least we can do to detect this is to give a warning on the js console.

warn if scale.expand_domain is used but domain was empty

---

js/src/Axis.ts

Fixes #1088.
Axis precision derivation requires at least two ticks.
Need to look for a better fix.

Set axis precision to 1 when there is only one tick

---

js/src/Axis.ts
js/src/ColorAxis.ts
js/src/DateColorScale.ts
js/src/DateScale.ts

*Issue number of the reported bug or feature request: #967 *
On the frontend dates are represented by timestamps (js native Date internally uses a timestamp). But, conversion of a mere date into a timestamp isn't really possible when it's not known in which timezone the date was recorded (2019-01-01 00:00 doesn't give enough information for conversion into a timestamp. 2019-01-01T00:00+02:00 does). As convention utc is used to generate a timestamp even though that timestamp will most likely not be the actual point in time when the date's event occurred. This is ok if the timestamp is converted back into a timezone-less date using utc.
In the frontend this conversion back was performed using the local timezone of the user's browser. The frontend uses javascript native conversion functions …

fix: DateScale doesn't apply browser timezone for ticks anymore

---

js/src/Lines.ts

Follow up of #1114
On initial draw, a handdraw would still not redraw the line / set the y data.
The problem was that the curve id wasn't set. `curves_sel` is initially an empty d3 selection, and after we attached data and added the nodes, we should reassign to `curves_sel` it seems. I thought d3 would keep the DOM and its selection in sync, but apparently it does not, or something else is going on.
Some more background why it doesn't work: https://github.com/bqplot/bqplot/blob/f2f01a3df3b7238ea126363bc5f93c70d89d1a92/js/src/HandDraw.ts#L118 use the id to set the data.

fix(Lines): set id properly on initial draw

---

js/src/Label.ts
js/src/Scatter.ts
js/src/ScatterBase.ts

This goes in the direction of putting more logic in the `Mark` super class, while cleaning the subclasses.

Remove ScatterBase.get_element_color and replace by Mark.get_mark_color

---

js/src/FlexLine.ts
js/src/Lines.ts

- `Lines.get_element_color` was exactly the same as its superclass's method `Mark.get_mark_color`
- `FlexLines.get_element_color` is slightly different, as it does not cycle through colors. But I feel like it would be good that all marks respects the same logic by cycling through the colors if there are multiple ones.

Remove redundant code from Lines/FlexLines

---

js/src/Lines.ts

- turn `that` into `this`
- make use of the superclass's `get_mark_opacity` method

Lines cleaning

---

js/less/bqplot.less

A dark theme and a light theme.
The original light theme is similar to ggplot, with a light gray background and white gridlines.
The original dark theme is a more "classic" wireframe style.
Since 0.12, bqplot makes use of the JupyterLab CSS variables for the coloring of the plot background to match the environment.
However, we kept two options for the bqplot styling: the "**gg**" style, similar to ggplot, and the "**classic**" style with the wireframe look. Roughly, "gg" looks like the original light theme in the with the JupyterLab light theme, and "classic" looks like the original dark theme in the JupyterLab dark theme
In this PR, I rework the colors to be closer to the original, especially in the dark theme. We still use JupyterLab variables.
I think these changes improve the visual …

Improve bqplot classic theme

---

js/src/ScatterBase.ts

We had an issue where the Scatter mark did not display labels passed to the constructor:
```javascript
import bqplot as bqp
import pandas as pd
sc_x = bqp.LinearScale()
sc_y = bqp.LinearScale()
scatter2 = bqp.Scatter(x=[1,2,3,4,5],
y=[1,2,3,4,5],
scales={'x': sc_x, 'y': sc_y},
display_legend=True,
colors=['red'],
labels=['Label displayed'],
stroke='black')
ax_y = bqp.Axis(label='Security 1 Returns', scale=sc_y, orientation='vertical', tick_format='.0%')
ax_x = bqp.Axis(label='Security 2', scale=sc_x)
bqp.Figure(axes=[ax_x, ax_y], marks=[scatter2], legend_location="top-left", display_legend=True)
```
Before:
After:

Fix legend not displaying labels on Scatter mark

---

bqplot/marks.py
examples/Marks/Object Model/Bars.ipynb
js/src/Bars.ts
js/src/BarsModel.ts

Introduce `opacity_mode` attribute to the `Bar` mark, which behaves like the `color_mode` attribute.
As discussed in https://github.com/bqplot/bqplot/issues/1163, we might need another mode that would allow retrieving the behavior that was in `0.11`.

Add opacity_mode attribute to the Bars class

---

js/less/bqplot.less

Simple fix to the colors applied to any data points with accompanying text, where the text appears orange instead of white, whilst on "Dark Theme" mode in Jupyter Lab. The specific attribute is the "names" attribute in the Scatter object.
```python
import bqplot as b
x_sc = b.LinearScale()
y_sc = b.LinearScale()
x_ax = b.Axis(scale=x_sc, label='X-axis')
y_ax = b.Axis(scale=y_sc, orientation='vertical', label='Y-axis')
scatter = b.Scatter(x=[1,2,3,4,5], y=[1,2,3,4,5], scales={'x': x_sc, 'y': y_sc}, colors=['#1B84ED'], names='1 2 3 4 5'.split())
figure = b.Figure(marks=[scatter], axes=[x_ax, y_ax], scale_x=x_sc, scale_y=y_sc, title='Scatter plot')
figure
```
Before:
After:

Fix scatter plot dot text color appearing orange in JLab dark theme

---

js/src/Bars.ts
js/src/test/bars.ts

The stroke color of the Bars mark is set to be that of the fill color, despite a default of "none". This creates an issue when the fill attribute of the Bars mark changes after being constructed, as the stroke does not change with it, leading to unintended behavior. 
Before:
After:

Fix stroke color being set fill color, despite default being "none".

---

js/src/Figure.ts

Resolves #607. There is a limitation in Firefox that `<svg>` elements must have `width` and `height` attributes set in order to be drawn to a canvas.

Fix saving png in Firefox

---

js/src/HistModel.ts

The migration from from D3 v3 to v4 introduced many changes, one of the more relevant ones for the Histogram mark is the d3.histogram() logic change. A change in logic introduced an issue where users passing a bins parameter to the Hist mark constructor were not getting the expected number of bins on the plot:
```python
from bqplot import Hist,Figure, Axis, LinearScale, OrdinalScale
import pandas as pd
df = pd.DataFrame([1,2,3,4],index=['A','B','C','D'])
x_sc = LinearScale()
y_sc = LinearScale()
hist = Hist(sample=df, scales={'sample': x_sc, 'count': y_sc}, bins=4)
ax_x = Axis(scale=x_sc, tick_format='0.2f')
ax_y = Axis(scale=y_sc, orientation='vertical')
Figure(marks=[hist], axes=[ax_x, ax_y], padding_y=0)
```
Before:
After:
Previously, we used to apply binning logic using the following …

Fix incorrect Histogram binning 

---

js/src/BarsModel.ts

This PR introduces a fix where a `color` attribute passed to a mark constructor does not show in the the tooltip.
```python
from bqplot import (
Bars, Figure, Tooltip, OrdinalScale, 
LinearScale, CATEGORY10
)
bar = Bars(x=[[1,2,3]],
y=[[1,2,3],[4,5,6]], 
colors=CATEGORY10,
color_mode='no_group',
tooltip=Tooltip(fields=['x', 'y', 'color']),
scales={'x': OrdinalScale(), 'y': LinearScale()}, 
color=['A', 'B', 'C','D','E','F'])
Figure(marks=[bar])
```
Before:
After:

Fix color attribute in tooltip

---

js/src/Bars.ts

This PR fixes an issue where updating the data (with partial NaNs) and Y-domain max traits simultaneously, results in an incorrect, oversize rectangle (see gif). It also adds a quick patch for NaNs which are passed to D3's scale, causing console log errors.
The issue is introduced in:
https://github.com/bqplot/bqplot/commit/e11e193339037ffbeec590eaaae33f50666b6641#diff-7fa0ead9ffe41bff2e2270d08efeb58aR365
It seems like we introduced two different transition names, but without any apparent benefit (which also causes the issue described above), so I have reverted that change.
Before:
After:

Fix Bars mark rendering oversize rectangle / NaN issues

---

bqplot/marks.py
js/src/Scatter.ts
js/src/ScatterBaseModel.ts

Requested in #1162, this PR adds horizontal and vertical offsets for the 'names' attribute in the Scatter mark, which overlays labels above each data point. It adds two float traitlets to the python side:
1. ~name_offset_x~ label_display_horizontal_offset (float, value denotes pixels, default value=None)
2. ~name_offset_y~ label_display_vertical_offset (float, value denotes pixels, default value=None)
Both of these are optional, and if no values are passed to the constructor, positioning will fall back to the default behaviour currently exhibited.

Add Scatter mark label positioning offset

---

js/package-lock.json
js/package.json
js/webpack.config.js

We can now run `npm run watch`
And the dev console gives us a much better path for the files:

Chore: js build polish

---

js/src/Axis.ts
js/src/ColorAxis.ts
js/src/Interaction.ts
js/src/Mark.ts
js/src/Selector.ts

I noticed that in many cases we listen to margin_update (using .on), but never detach it.
In all cases, the context was this, so we could replace it using this.listenTo, which will automatically detach after calling .remove().

fix: margin_update event listeners were never detached

---

js/src/BrushSelector.ts
js/src/DateScaleModel.ts
js/src/LinearScaleModel.ts
js/src/OrdinalScaleModel.ts

Fix #1224
Example:
```python
from bqplot import *
from ipywidgets import *
from bqplot.interacts import *
scale_x1 = DateScale()
scale_y1 = OrdinalScale()
x = np.arange('2020-01-01', '2020-04-01', dtype='datetime64[M]')
scatter1 = Scatter(x=x, y=[3,2,1], scales={'x':scale_x1, 'y':scale_y1})
fig1 = Figure(marks=[scatter1], interaction=BrushSelector(x_scale=scale_x1,
y_scale=scale_y1, marks=[scatter1]), background_style={'fill':'#eee'})
fig1
```

fix: preserve scale type in selected attribute, fixes #1224

---

js/src/Figure.ts
js/src/test/figure.ts

Closes https://github.com/spacetelescope/jdaviz/issues/270
```python
from bqplot import *
from ipywidgets import *
from bqplot.interacts import *
scale_x1 = DateScale()
scale_y1 = LinearScale()
x = np.arange('2010-01-01', '2020-04-01', dtype='datetime64[D]')
y1 = np.cumsum(np.random.random(x.shape) - 0.5)
line1 = Lines(x=x, y=y1, scales={'x':scale_x1, 'y':scale_y1})
y2 = np.cumsum(np.random.random(x.shape) - 0.5)
line2 = Lines(x=x, y=y2, scales={'x':scale_x1, 'y':scale_y1})
fig1 = Figure(marks=[line1, line2], interaction=BrushSelector(x_scale=scale_x1,
y_scale=scale_y1, marks=[line1]), background_style={'fill':'#eee'})
fig1
fig1.marks = [line1, line2]
fig1.marks = []
```
Fix coming, would first like to see this fail on CI.

fix: marks were not removed when changed before views created

---

bqplot/marks.py
examples/Applications/Feature_Vector_Distribution-Iris-Digits.ipynb
examples/Marks/Object Model/Scatter.ipynb
examples/Marks/Object Model/ScatterMega.ipynb
examples/Marks/Pyplot/Scatter.ipynb
js/src/Label.ts
js/src/Scatter.ts
js/src/ScatterBase.ts
js/src/ScatterBaseModel.ts
js/src/ScatterGL.ts
js/src/ScatterGLModel.ts
js/src/test/scatter-mega.ts

Deprecate Scatter's `default_opacities` in favor of `opacities` (`default_colors` was deprecated in favor of `colors` in bqplot `0.8.4`).
Other marks had `opacities` instead of `default_opacities`, so this will make bqplot's API more homogeneous.
This is the first of several PRs for making `Mark`'s implementation more general, by adding common marks logic inside of it. For this purpose we need to make marks APIs more homogeneous.

Scatter: default_opacities -> opacities

---

pyproject.toml
setup.py

Follow-up to https://github.com/bqplot/bqplot/pull/1235 and https://github.com/jupyter/jupyter-packaging/pull/54.
Using the latest `jupyter-packaging~=0.7.7` which includes `skip_if_exists`.

Use skip_if_exists from upstream jupyter-packaging

---

js/src/FlexLine.ts

This removes the JS exceptions when using `FlexLine`.
Now I think `FlexLine` should not inherit from `Line` anymore, they don't have a lot in common, only scales and listeners members. THey don't share common behavior, so it could be worth refactoring this part of bqplot.

Removed call to super.relayout in FlexLine

---

js/package.json

d3-selection has global state (the event) that is obtained
using `require("d3-selection").event`. If multiple copies of this
js module exists in the frontend, they will not read eachother's
events.
This is required for 3rd party libraries, such as bqplot-image-gl
to be able to read the last d3 event.
Since Jupyter Lab will deduplicate direct dependencies, we only need
to add the d3-selection as an explicit dependency, and it will be
shared with other extensions.

Feature: enable deduplication of d3-selection for shared browser events

---

test-environment.yml
tests/selector_test.py

This requires us to first drop python2.7

if we drop python2, we can use unittest.mock

---

js/src/Boxplot.ts
js/src/BoxplotModel.ts

Fix #1236
Fix support for Boxplot and add "x", "median", "q1" and "q3" fields

Fix Boxplot tooltips

---

install.json
setup.py

To give more information to end users on how to uninstall the prebuilt `bqplot` extension for JupyterLab 3.0.

Add install.json with uninstall instructions

---

js/src/Axis.ts

I introduced an issue in #1282 
The Axis was using a numbers formatting for dates because `scale instanceof LinearScale` is true for a `DateScale`.

Fix tickmarks for dates

---

js/src/PanZoom.ts

Fixes #1333 
This is now using the d3-drag module, which takes care of this.

fix: pan zoom kept panning when mouse was released outside of figure

---

js/src/Bars.ts
js/src/Boxplot.ts
js/src/BrushSelector.ts
js/src/Graph.ts
js/src/GridHeatMap.ts
js/src/Hist.ts
js/src/LassoSelector.ts
js/src/Map.ts
js/src/Mark.ts
js/src/OHLC.ts
js/src/PanZoom.ts
js/src/Pie.ts
js/src/utils.ts

Similar problem as described in #1276
In my case, I had ipyvolume installed, which had it's own copy of d3 and d3-selection. Bqplot also has its own d3-selection, ipyvolume sets it's d3.event, and bqplot read d3.event from its private module, giving null:
This prevented zooming from working with the PanZoom Interact, giving:
```
PanZoom.js:168 Uncaught TypeError: Cannot read property 'preventDefault' of null
```
According to:
https://developer.mozilla.org/en-US/docs/Web/API/Window/event
This is supported by all browsers.
I think a prettier solution would be to move to d3-selection 2.0, which supports the event being passed as argument. However, I'm not sure that this will work if 3rd party libraries (such as ipyvolume) still have the older version of d3-selection.

fix: under jlab3, d3.event can be null because of duplicate d3 modules

---

js/src/Figure.ts

Fixes #1367
The following screenshot could be saved with the save button:

Fix issue when saving figure with accents

---

bqplot/marks.py

At present, the Python widget event dispatching is implemented with a giant `if ..: elif ...:` block, which is both unperformant and more work to maintain. This moves everything into a dict defined in `__init__`.

Use dict to dispatch event handlers on Python side

---

bqplot/figure.py
bqplot/interacts.py
bqplot/marks.py

__DeprecationWarning: Keyword `trait` is deprecated in traitlets 5.0, use `value_trait` instead__
Fixes the following pytest warnings seen [in our GitHub Actions](https://github.com/bqplot/bqplot/actions):
```
=============================== warnings summary ===============================
bqplot/marks.py:167
/home/runner/work/bqplot/bqplot/bqplot/marks.py:167: DeprecationWarning: Keyword `trait` is deprecated in traitlets 5.0, use `value_trait` instead
scales = Dict(trait=Instance(Scale)).tag(sync=True, **widget_serialization)
bqplot/interacts.py:157
/home/runner/work/bqplot/bqplot/bqplot/interacts.py:157: DeprecationWarning: Keyword `trait` is deprecated in traitlets 5.0, use `value_trait` instead
scales = Dict(trait=List(trait=Instance(Scale)))\
bqplot/figure.py:135 …
```

Keyword "trait" is deprecated in traitlets 5.0

---

bqplot/default_tooltip.py
bqplot/interacts.py
bqplot/market_map.py
bqplot/marks.py
bqplot/pyplot.py
bqplot/scales.py
bqplot/traits.py
examples/Applications/Feature_Vector_Distribution-Iris-Digits.ipynb
examples/Applications/Outlier Detection.ipynb
examples/Introduction.ipynb
examples/Marks/Object Model/Label.ipynb
examples/Marks/Pyplot/Label.ipynb
examples/Tutorials/Gaussian Density Widget.ipynb
examples/Tutorials/Object Model.ipynb
examples/Tutorials/Pyplot.ipynb
js/src/Bars.ts
js/src/Graph.ts
js/src/Hist.ts
js/src/Interaction.ts
js/src/MarketMap.ts
js/src/OHLC.ts
js/src/ScaleModel.ts
js/src/ScatterBase.ts
js/src/test/figure.ts
ui-tests/tests/bqplot.test.ts

[`codespell --ignore-words-list="afterall,curvelinear,hist" --skip="*.csv,*.json,*.lock"`](https://github.com/codespell-project/codespell)

Fix typos discovered by codespell

---

js/src/Figure.ts

Fixes #1359
This caused the event listener fix introduced in https://github.com/bqplot/bqplot/pull/1347 to be removed again.

fix: changing an interaction causes it to remove the old view twice

---

bqplot/marks.py
bqplot/traits.py
pytest.ini
tests/binary_serialization_test.py
tests/marks_test.py

This will clean up not only our test output, but also others, we only got one left from traittypes now:
```
$ py.test tests --pdb                         jdaviz-dev
=============================== test session starts ================================
platform darwin -- Python 3.7.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/maartenbreddels/src/bqplot, configfile: pytest.ini
plugins: asdf-2.8.0, anyio-3.0.1
collected 10 items                                                                 
tests/binary_serialization_test.py .....                                     [ 50%]
tests/marks_test.py ....                                                     [ 90%]
tests/selector_test.py .                                                     [100%]
================================= …
```

chore: fix deprecation warnings/issues and let pytest catch them

---

bqplot/figure.py
js/src/Figure.ts
js/src/FigureModel.ts

A solution for #1393
Usage:
```python
def on_png_received(data):
with open('mychart.png', 'bw') as f:
f.write(data)
figure.get_png_data(on_png_received)
```

feat: make a PNG export of the figure available in the kernel

---

js/shaders/scales.glsl
js/shaders/scatter-vertex.glsl
js/src/ScatterGL.ts

ScatterGL assumed the scales to be linear, this adds support for log scales.
This would need to be ported to bqplot-gl and master as well.

feat: log scale support for ScatterGL Mark

---

.github/workflows/build.yml

With the new bot, this becomes useless

CI: Remove "update snapshots" step

---

js/src/Figure.ts

This makes bqplot-image-gl work with bqplot 0.12.x and future versions.

fix: Figure.update_gl shim make for bqplot 0.12 compatibility

---

js/package.json

`main` currently points to `lib/index.js` which is the transpiled, non-webpacked source. When accessing `bqplot` via a CDN it will direct to `browser` then `main`, so in this PR we point `browser` at the dist code.
CC for details:
https://github.com/voila-dashboards/voila/pull/1154
https://github.com/voila-dashboards/voila/issues/1128
Add `browser` field
Should be none.
Should be none.

Add browser field to package.json

---

bqplot/interacts.py
bqplot/market_map.py
bqplot/marks.py

There are small typos in:
- bqplot/interacts.py
- bqplot/market_map.py
- bqplot/marks.py
Fixes:
- Should read `tooltip` rather than `tootip`.
- Should read `representing` rather than `represetning`.
- Should read `interpolation` rather than `interpolatoin`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

test-environment.yml

Signed-off-by: Itay Dafna <i.b.dafna@gmail.com>
This PR pins the nodejs to version 16 to avoid issues with node-pre-gyp installations with nodejs 18 on  the galata bot.

Pin NodeJS version in ui-testing environment

---

bqplot/marks.py
js/src/Lines.ts

Closes [#1510 ](https://github.com/bqplot/bqplot/issues/1510)
Add TypeScript references for the missing interpolation types and update the Python docstring to reflect the available options. I used the official d3 [docs](https://github.com/d3/d3-shape/blob/v3.1.0/README.md#line) to check the right references.
Add compatibility for 7 interpolation modes that were supported on the Python side, but missing on the JS side:
- basis-open
- basis-closed
- bundle
- cardinal-open
- cardinal-closed
- step-before
- step-after
N/A

Fix missing interpolation options

---

setup.cfg

- addresses https://github.com/conda-forge/bqplot-feedstock/pull/86
- the feedstock will fail downstream once these are removed: this is fine
- removes the `tests` top-level module, which conflicts with other distributions
- as it's "last-in-wins," this is not a reliable place to put them
- some downstreams like `constructor` actively choke on them
- adds some JupyterLab trove classifiers
- prospective users would be able to see bqplot in the PyPI browse UI when looking for JupyterLab extensions
- n/a

exclude tests top-level package, add some JupyterLab trove classifiers

---

js/src/Figure.ts
js/src/Mark.ts
js/src/MarketMap.ts
js/src/utils.ts

The luminoWidget accessor does not work undo ipywidgets 7

Forward port #1523 Fix pWidget accessor in the case of ipywidgets 7

---

bqplot/marks.py
bqplot/pyplot.py
examples/Marks/Object Model/Lines.ipynb
examples/Marks/Pyplot/Lines.ipynb
js/src/Markers.ts

Closes #1457 
See below 
This adds three more scatter marker shapes:
+ `plus`, which makes the shape `+`, with the shortcut `p`
+ `crosshair`, which makes the shape `×`, with the shortcut `x`
+ `point`, which makes a small circle, with the shortcut `.`
N/A

Add +, x and . as markers

---

bqplot/axes.py
examples/Advanced Plotting/Axis Properties.ipynb
js/src/Axis.ts
js/src/AxisModel.ts

This allows any custom labeling from the kernel side, and code reuse of labeling code for bqplot and matplotlib.
While I think it's always good to have more scales, there is always a use case of not being able to let the scales+axis do what you want.
Using `tick_values` was already useful, but in combination with the new `tick_labels` (dict that maps values to labels) users have ultimate freedom to position and format the ticks on that axis.
Listening to min and max on the scales, we can update the ticks when we pan (no code example for that yet).
e.g.:
```python
def locator(xmin, xmax, ticks=5):
return (xmin + (xmax - xmin) * np.linspace(0, 1, ticks) ** 0.5).astype(int)
def formatter(x, pos=None):
return f'{100 * int(x):.1f}nm'
```
We can use that for matplotlib (code …

feature: custom axis labeling from kernel side (tick_labels).

---

js/src/Figure.ts

Extend bypass relayout logic to include margins
Changing margins results in an updated figure
To reproduce:
```python
size = 100
scale = 100.0
np.random.seed(0)
x_data = np.arange(size)
y_data = np.cumsum(np.random.randn(size) * scale)
fig = plt.figure()
plt.plot(y_data)
fig
```
```python
fig.fig_margin = {'top': 0, 'bottom': 0, 'left': 30, 'right': 0}
```

fix: figure is not updating when margins change

---

examples/Applications/Equity Index Performance/Time Series.ipynb
js/package.json
js/src/Figure.ts
js/yarn.lock
test-environment.yml

no issue for this yet
Use a combination of `IntersectionObserver` and `ResizeObserver` instead of lumino-events to control relayouts, so this works when lumino-events are not available. This is the case when embedding bqplot in an ipyvuetify-template.
The typescript version was changed to have type support for ResizeObserver.
before:
https://user-images.githubusercontent.com/46192475/194905971-9cd46938-2f32-4f91-8c0d-716abe058276.mp4
after:
https://user-images.githubusercontent.com/46192475/194906020-9d7f377f-3c61-4bfe-9f2e-d05a7d8d33ee.mp4
To reproduce:
```python
pip install ipyvuetify ipygoldenlayout
```
```python
import ipyvuetify as v
import traitlets
from ipygoldenlayout import GoldenLayout
import ipywidgets
size = 100
scale = 100.0 …
```

fix: display and resize plots when not in a lumino context

---

js/src/PanZoom.ts

In Firefox and Safari, panning doesn't work correctly when a plot's parent is rotated by CSS.
The panning issue is caused by getScreenCTM() in https://github.com/d3/d3-selection/blob/679346930e41a4037ef72d937b425bbe4d865ab1/src/point.js#L7, which doesn't take the viewport transforms into account in Firefox (https://stackoverflow.com/questions/71368779/svg-getscreenctm-does-not-account-for-css-transforms-in-firefox) and Safari
As seen here: https://github.com/spacetelescope/jdaviz/pull/1384#issuecomment-1386107387
To reproduce, run the following code in Firefox or Safari:
```python
from bqplot.interacts import PanZoom
import ipywidgets as widgets
import bqplot as bq
from traitlets import link
from collections import OrderedDict
import ipyvue
x_sc = bq.LinearScale()
y_sc …
```

fix: panning in a by CSS rotated plot doesn't work correctly

---

js/src/Figure.ts

The intersectObserver, used to determine if an element is visible, can contain multiple entries for the same target element. The last entry represents the last observed state, so we should use the last instead of the first for the visibility test.
See: https://github.com/spacetelescope/jdaviz/issues/2129

fix: resize not always working

---

setup.cfg

We are unlikely to ever be affected by breaking changes in numpy because we do not use a large surface area.
See https://iscinumpy.dev/post/bound-version-constraints/#tldr
'Anyone can fix a missing cap, but users cannot fix an over
restrictive cap causing solver errors.'
Fixes https://github.com/spacetelescope/jdaviz/issues/2259

fix: remove numpy upper bound pin

---

js/src/Figure.ts
js/src/utils.ts

On the screen, it is not the computed background color that is seen by a user. Since DOM elements can be transparent, the background color might be one of the parent elements. This is why we need to traverse the DOM tree to find the background color of the first non-transparent parent element.
A more sophisticated solution would be to also use blending when there is a non-fully transparent background color. I think that might be a bit overkill for now.
See also https://github.com/spacetelescope/jdaviz/pull/2264#issuecomment-1612052525

fix: background color of figure was not computed properly

---

js/src/Figure.ts
js/src/utils.ts

On the screen, it is not the computed background color that is seen by a user. Since DOM elements can be transparent, the background color might be one of the parent elements. This is why we need to traverse the DOM tree to find the background color of the first non-transparent parent element.
A more sophisticated solution would be to also use blending when there is a non-fully transparent background color. I think that might be a bit overkill for now.
See also https://github.com/spacetelescope/jdaviz/pull/2264#issuecomment-1612052525

Backport #1603 fix: background color of figure was not computed properly (#1603)

---

js/src/Bars.ts
js/src/BarsModel.ts

This also allows the use of bars with log scales
We currently subtract `base` (baseValue in js code) each time from the value, which caused stacked bars to not show correct values. See demonstration of the bug:
Code to reproduce:
```python
import bqplot
N = 1000
np.random.seed(42)
log = False
sx = bqplot.LinearScale(min=0, max=4)
sy = bqplot.LinearScale(min=-2, max=6)
if log:
sy = bqplot.LogScale(min=0.1, max=10)
fig = plt.figure(scale_x=sx, scale_y=sy)
x, y, c = np.random.normal(size=(3, N))
if log:
mark = plt.bar([1,2,3], [[1, 1, 1], [2, 3, 4]], base=0.1, color=["orange", "green"], scales={'x': sx, 'y': sy})
else:
mark = plt.bar([1,2,3], [[1, -1, 1], [2, -3, 4]], base=0, color=["orange", "green"], scales={'x': sx, 'y': sy})
plt.show() …
```

fix: properly treat Bar.base with stacked Bars

---

js/src/LinearScaleModel.ts
test-environment.yml

In #1619 we reset the domain to (0, 1) when no data is present. However, this only matters when the min/max are not set.
Issue found in https://github.com/spacetelescope/jdaviz/pull/2661

fix: domain should not be reset when min/max are set

---

pyproject.toml

Use modern jupyter_packaging so this can build in Python 3.13
Example failure log: https://github.com/spacetelescope/jdaviz/actions/runs/11278687750/job/31367720187?pr=3210
xref https://github.com/spacetelescope/jdaviz/pull/3210
cc @maartenbreddels @dhomeier

BLD: Use modern jupyter_packaging

---

examples/Marks/Object Model/HeatMap.ipynb
examples/Marks/Pyplot/HeatMap.ipynb
test-environment.yml

According to https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.misc.ascent.html

fix: ascent is now in scipy.datasets instead of scipy.misc

---

js/src/Figure.ts

The character \xa0 is converted to &nbsp; when .outerHTML() is called, causing an error in the data-URL where the outer HTML is used.
(cherry picked from commit 4d5c2932d8d55e1af96e7129f0550c18c0c3b977)

Backport PR bqplot#1644: fix: save_png doesn't work when character \xa0 is used (#1644)
